/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  stream_Stream_PointerObject.c */
/* class: PointerObject */

#include <ferite.h>       /* we need this without a doubt */
#include "stream_header.h"  /* this is the module header */

