/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "stream_header.h"  /* this is the module header */

void ferite_stream_register()
{
      ferite_module_register_native_function( "Stream.Stream.flush_", ferite_stream_Stream_Stream_flush_ );
      ferite_module_register_native_function( "Stream.Stream.setAggressive_b", ferite_stream_Stream_Stream_setAggressive_b );
      ferite_module_register_native_function( "Stream.Stream.eos_", ferite_stream_Stream_Stream_eos_ );
      ferite_module_register_native_function( "Stream.Stream.getError_", ferite_stream_Stream_Stream_getError_ );
      ferite_module_register_native_function( "Stream.Stream.__read___n", ferite_stream_Stream_Stream___read___n );
      ferite_module_register_native_function( "Stream.Stream.read_n", ferite_stream_Stream_Stream_read_n );
      ferite_module_register_native_function( "Stream.Stream.printf_sE", ferite_stream_Stream_Stream_printf_sE );
      ferite_module_register_native_function( "Stream.Stream.clearInputBuffer_", ferite_stream_Stream_Stream_clearInputBuffer_ );
      ferite_module_register_native_function( "Stream.Stream.__write___s", ferite_stream_Stream_Stream___write___s );
      ferite_module_register_native_function( "Stream.Stream.write_s", ferite_stream_Stream_Stream_write_s );
      ferite_module_register_native_function( "Stream.Stream.writeln_s", ferite_stream_Stream_Stream_writeln_s );
      ferite_module_register_native_function( "Stream.Stream.setEndOfLine_s", ferite_stream_Stream_Stream_setEndOfLine_s );
      ferite_module_register_native_function( "Stream.Stream.ungetc_s", ferite_stream_Stream_Stream_ungetc_s );
      ferite_module_register_native_function( "Stream.Stream._readln_", ferite_stream_Stream_Stream__readln_ );
      ferite_module_register_native_function( "Stream.Stream.destructor_", ferite_stream_Stream_Stream_destructor_ );
      ferite_module_register_native_function( "Stream.Stream.constructor_", ferite_stream_Stream_Stream_constructor_ );
      ferite_module_register_native_function( "Stream.StdioStream.eos_", ferite_stream_Stream_StdioStream_eos_ );
      ferite_module_register_native_function( "Stream.StdioStream.__read___n", ferite_stream_Stream_StdioStream___read___n );
      ferite_module_register_native_function( "Stream.StdioStream.__write___s", ferite_stream_Stream_StdioStream___write___s );
      ferite_module_register_native_function( "Stream.StdioStream.getDescriptor_", ferite_stream_Stream_StdioStream_getDescriptor_ );
      ferite_module_register_native_function( "Stream.StdioStream.__close___", ferite_stream_Stream_StdioStream___close___ );
      ferite_module_register_native_function( "Stream.StdioStream.constructor_n", ferite_stream_Stream_StdioStream_constructor_n );
}

void ferite_stream_init( FeriteScript *script )
{
}

void ferite_stream_deinit( FeriteScript *script )
{
}

void ferite_stream_unregister()
{
}

