/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __stream_HEADER__
#define __stream_HEADER__

#include <ferite.h>

FERITE_API void ferite_stream_register();
FERITE_API void ferite_stream_unregister();
FERITE_API void ferite_stream_init( FeriteScript *script );
FERITE_API void ferite_stream_deinit( FeriteScript *script );

    /* Start user defined header code */


#include "../../config.h"
#include "../../libs/aphex/include/aphex.h"
#include "util_stream.h"

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_flush_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_setAggressive_b );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_eos_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_getError_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream___read___n );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_read_n );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_printf_sE );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_clearInputBuffer_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream___write___s );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_write_s );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_writeln_s );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_setEndOfLine_s );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_ungetc_s );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream__readln_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_destructor_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_Stream_constructor_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream_eos_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream___read___n );
FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream___write___s );
FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream_getDescriptor_ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream___close___ );
FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream_constructor_n );

#endif /* __stream_HEADER__ */
