/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  stream_Stream_StdioStream.c */
/* class: StdioStream */

#include <ferite.h>       /* we need this without a doubt */
#include "stream_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream_eos_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 601 "stream.fec"

 struct Stream *Stream = self->odata;
 if( Stream->eos && Stream->input_buffer.length == 0 )
 {
 FE_RETURN_TRUE;
 }
 FE_RETURN_FALSE;
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream___read___n )
{
   double c = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &c );

   { /* Main function body. */
#line 561 "stream.fec"

 struct Stream *Stream = self->odata;
 FeriteVariable *in = NULL;
 in = fe_new_str_static("read", NULL, (int)c, FE_CHARSET_DEFAULT );
 FE_STRLEN(in) = read( Stream->file_descriptor, FE_STR2PTR(in), (int)c );
 Stream->eos = (FE_STRLEN(in) <= 0 ? FE_TRUE : FE_FALSE);
 if( FE_STRLEN(in) == -1 )
 {
 ferite_error( script, errno, "StdioStream: Read: %s (%d)\n", strerror( errno ), errno );
 if( Stream->errmsg != NULL )
 {
 ffree( Stream->errmsg );
 }
 Stream->errmsg = fstrdup( strerror( errno ) );
 FE_STRLEN(in) = 0;
 }
 FE_RETURN_VAR( in );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream___write___s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 579 "stream.fec"

 struct Stream *Stream = self->odata;
 int ret = 0;
 ret = write( Stream->file_descriptor, s->data, s->length );
 if( ret == -1 )
 {
 ferite_error( script, errno, "StdioStream: Write: %s (%d)\n", strerror( errno ), errno );
 if( Stream->errmsg != NULL )
 {
 ffree( Stream->errmsg );
 }
 Stream->errmsg = fstrdup( strerror( errno ) );
 FE_RETURN_LONG( 0 );
 }
 FE_RETURN_LONG( ret );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream_getDescriptor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 609 "stream.fec"

	struct Stream *s = self->odata;
	FE_RETURN_LONG(s->file_descriptor);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream___close___ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 595 "stream.fec"
 
 struct Stream *Stream = self->odata;
 if( Stream->file_descriptor != -1 && Stream->file_descriptor != 0 && Stream->file_descriptor != 1 && Stream->file_descriptor != 2 )
 close( Stream->file_descriptor );
	STREAM_RESET(Stream);
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_stream_Stream_StdioStream_constructor_n )
{
   double fd = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &fd );

   { /* Main function body. */
#line 549 "stream.fec"

 struct Stream *Stream = NULL;
 FeriteVariable *c = ferite_create_object_variable_with_data( script, "StdioStream", self, FE_STATIC ); 
 ferite_variable_destroy( script, ferite_object_call_super( script, c, NULL ) ); 
 ferite_variable_destroy( script, c );
 
 Stream = self->odata;
 Stream->eos = FE_FALSE;
 Stream->file_descriptor = fd;
 Stream->read = ferite_object_get_function( script, self, "__read__" );
 Stream->write = ferite_object_get_function( script, self, "__write__" );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

