/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __number_HEADER__
#define __number_HEADER__

#include <ferite.h>

FERITE_API void ferite_number_register();
FERITE_API void ferite_number_unregister();
FERITE_API void ferite_number_init( FeriteScript *script );
FERITE_API void ferite_number_deinit( FeriteScript *script );

    /* Start user defined header code */



#include <math.h>
#include <stdlib.h>

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_number_Number_sqrt_n );
FE_NATIVE_FUNCTION( ferite_number_Number_atan_n );
FE_NATIVE_FUNCTION( ferite_number_Number_tan_n );
FE_NATIVE_FUNCTION( ferite_number_Number_log10_n );
FE_NATIVE_FUNCTION( ferite_number_Number_log_n );
FE_NATIVE_FUNCTION( ferite_number_Number_ceil_n );
FE_NATIVE_FUNCTION( ferite_number_Number_isLong_n );
FE_NATIVE_FUNCTION( ferite_number_Number_acos_n );
FE_NATIVE_FUNCTION( ferite_number_Number_cos_n );
FE_NATIVE_FUNCTION( ferite_number_Number_floor_n );
FE_NATIVE_FUNCTION( ferite_number_Number_round_n );
FE_NATIVE_FUNCTION( ferite_number_Number_atan2_nn );
FE_NATIVE_FUNCTION( ferite_number_Number_abs_n );
FE_NATIVE_FUNCTION( ferite_number_Number_asin_n );
FE_NATIVE_FUNCTION( ferite_number_Number_sin_n );
FE_NATIVE_FUNCTION( ferite_number_Number_pow_nn );
FE_NATIVE_FUNCTION( ferite_number_Number_isDouble_n );
FE_NATIVE_FUNCTION( ferite_number_Number_exp_n );

#endif /* __number_HEADER__ */
