/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "number_header.h"  /* this is the module header */

void ferite_number_register()
{
      ferite_module_register_native_function( "Number.sqrt_n", ferite_number_Number_sqrt_n );
      ferite_module_register_native_function( "Number.atan_n", ferite_number_Number_atan_n );
      ferite_module_register_native_function( "Number.tan_n", ferite_number_Number_tan_n );
      ferite_module_register_native_function( "Number.log10_n", ferite_number_Number_log10_n );
      ferite_module_register_native_function( "Number.log_n", ferite_number_Number_log_n );
      ferite_module_register_native_function( "Number.ceil_n", ferite_number_Number_ceil_n );
      ferite_module_register_native_function( "Number.isLong_n", ferite_number_Number_isLong_n );
      ferite_module_register_native_function( "Number.acos_n", ferite_number_Number_acos_n );
      ferite_module_register_native_function( "Number.cos_n", ferite_number_Number_cos_n );
      ferite_module_register_native_function( "Number.floor_n", ferite_number_Number_floor_n );
      ferite_module_register_native_function( "Number.round_n", ferite_number_Number_round_n );
      ferite_module_register_native_function( "Number.atan2_nn", ferite_number_Number_atan2_nn );
      ferite_module_register_native_function( "Number.abs_n", ferite_number_Number_abs_n );
      ferite_module_register_native_function( "Number.asin_n", ferite_number_Number_asin_n );
      ferite_module_register_native_function( "Number.sin_n", ferite_number_Number_sin_n );
      ferite_module_register_native_function( "Number.pow_nn", ferite_number_Number_pow_nn );
      ferite_module_register_native_function( "Number.isDouble_n", ferite_number_Number_isDouble_n );
      ferite_module_register_native_function( "Number.exp_n", ferite_number_Number_exp_n );
}

void ferite_number_init( FeriteScript *script )
{
}

void ferite_number_deinit( FeriteScript *script )
{
}

void ferite_number_unregister()
{
}

