/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __test_HEADER__
#define __test_HEADER__

#include <ferite.h>

FERITE_API void ferite_test_register();
FERITE_API void ferite_test_unregister();
FERITE_API void ferite_test_init( FeriteScript *script );
FERITE_API void ferite_test_deinit( FeriteScript *script );

    /* Start user defined header code */



#include <stdio.h>
#include "utility.h"


    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_test_Test___teardown___ );
FE_NATIVE_FUNCTION( ferite_test_Test_run_s );
FE_NATIVE_FUNCTION( ferite_test_Test___shakedown___ );
FE_NATIVE_FUNCTION( ferite_test_Test___misc___ );
FE_NATIVE_FUNCTION( ferite_test_Test___setup___ );

#endif /* __test_HEADER__ */
