/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  test_Test.c */
/* class: Test */

#include <ferite.h>       /* we need this without a doubt */
#include "test_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_test_Test___teardown___ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 255 "test.fec"

 FE_RETURN_LONG( 0 );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_test_Test_run_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 49 "test.fec"

 FeriteNamespaceBucket *nsb;
 FeriteNamespace *ns;
 FeriteHashBucket *buk,*res;
 FeriteHash *hash;
 FeriteIterator *iter;
 FeriteClass *class;
 FeriteFunction *fnc;
 FeriteClass *cls;
 FeriteVariable *tot_impl, *tot_fail, *tot_success, *tot_ignored, *var;
 char *key;
 int rate=0,count=0,ret,quiet=0;

 tot_impl = ferite_object_get_var( script, self, "tot_impl");
 tot_fail = ferite_object_get_var( script, self, "tot_fail");
 tot_success = ferite_object_get_var( script, self, "tot_success");
 tot_ignored = ferite_object_get_var( script, self, "tot_ignored" );
 var = ferite_object_get_var( script, self, "beQuiet");
 quiet = VAI(var);

 if(!quiet)
 printf("===================================\n");

/*
 * This will call the __setup__ method, and if returning other than 0 bail out.
 */

 if((ret = Test_execute_function(script, super, self, "__setup__")))
 {
 if(!quiet)
 printf("<FAILED>__setup__() returned %d, Aborting.\n",ret);
 FE_RETURN_LONG(100);
 }

/*
 * Check if passed name is Namespace or Class, and walk all functions/methods.
 */

 iter = ferite_create_iterator(script);
 if(( nsb = ferite_find_namespace(script,script->mainns, name->data, 0) ) == NULL)
 printf("[PANIC] Unknown class or namespace: %s\n",name->data);
 else if(nsb->type == FENS_CLS)
 {
 if(!quiet)
 printf("Class: %s\n", name->data);
 cls = (FeriteClass *)nsb->data;
 /* while( cls != NULL ) */ /* no parent */
 {
 FeriteHash *check[] = { cls->object_methods, cls->class_methods };
 int i = 0;
 
 for( i = 0; i < 2; i++ )
 {
 memset( iter, 0, sizeof(FeriteIterator) );
 while( (buk = ferite_hash_walk(script,check[i],iter)) != NULL )
 {
 fnc = (FeriteFunction*)buk->data;
 if(strcmp("constructor",fnc->name) == 0 || strcmp("destructor",fnc->name) == 0 || fnc->state != FE_ITEM_IS_PUBLIC)
 {
 /* Constructor/Destructor */
 }
 else if((res = ferite_hash_get(script,self->functions,fnc->name)) == NULL)
 {
 if(!quiet)
 printf("<FAILED> %sfunction %s(), not implemented\n", (fnc->is_static ? "static " : ""), fnc->name);
 VAI(tot_impl)++;
 }
 else
 {
 if( (ret = Test_execute_function(script, super, self, fnc->name)) != 0 )
 {
 if(!quiet)
 {
 if( ret > -2 )
 printf("<FAILED> %sfunction %s() returned error: %d\n",(fnc->is_static ? "static " : ""),fnc->name, ret);
 else
 printf("{IGNORE} %sfunction %s() ignored\n",(fnc->is_static ? "static " : ""),fnc->name); 
 
 if( ret == -1 )
 {
 char *errmsg = ferite_get_error_log( script );
 printf( "<ERRORLOG>\n%s", errmsg );
 ffree( errmsg );
 }
 }
 
 if( ret > -2 )
 VAI(tot_fail)++;
 else
 VAI(tot_ignored)++;
 
 ferite_reset_errors( script );
 }
 else
 {
 if(!quiet)
 printf("[PASSED] %sfunction %s()\n",(fnc->is_static ? "static " : ""),fnc->name);
 VAI(tot_success)++;
 }
 }
 }
 }
 /* cls = cls->parent; */ /* no parent, we assume other test cases deal with them */
 }
 }
 else if( nsb->type == FENS_NS )
 {
 if(!quiet)
 printf("Namespace: %s\n",name->data);
 hash = ((FeriteNamespace *)nsb->data)->code_fork;
 while( (buk = ferite_hash_walk(script,hash,iter)) != NULL )
 {
 nsb = (FeriteNamespaceBucket*)buk->data;
 /* Only test functions */
 if(nsb->type != FENS_FNC)
 continue;
 fnc = nsb->data;
 if((res = ferite_hash_get(script,self->functions,fnc->name)) == NULL)
 {
 if(!quiet)
 printf("<FAILED> function %s(), not implemented\n",fnc->name);
 VAI(tot_impl)++;
 }
 else
 {
 if((ret = Test_execute_function(script, super, self, fnc->name)))
 {
 if(!quiet)
 {
 if( ret > -2 )
 printf("<FAILED> function %s() returned error: %d\n",fnc->name, ret);
 else
 printf("{IGNORE} function %s() is ignored\n",fnc->name, ret);
 
 if( ret == -1 )
 {
 char *errmsg = ferite_get_error_log( script );
 printf( "<ERRORLOG>\n%s", errmsg );
 ffree( errmsg );
 }
 }
 if( ret > -2 )
 VAI(tot_fail)++;
 else
 VAI(tot_ignored)++;
 ferite_reset_errors( script );
 }
 else
 {
 if(!quiet)
 printf("[PASSED] function %s()\n",fnc->name);
 VAI(tot_success)++;
 }
 }
 }
 }
 else
 {
 printf("[ABORT] This test only works with Classes or Namespaces\n");
 }

/*
 * Call the __misc__, __shakedown__ and __teardown methods,
 * and if returning other than 0, we fail the complete test.
 */

 if((ret = Test_execute_function(script, super, self, "__misc__")))
 {
 if(!quiet)
 printf("<FAILED> function %s() returned error: %d\n","__misc__", ret);
 VAI(tot_fail)++;
 }
 if((ret = Test_execute_function(script, super, self, "__shakedown__")))
 {
 if(!quiet)
 printf("<FAILED> function %s() returned error: %d\n","__shakedown__", ret);
 VAI(tot_fail)++;
 }
 if((ret = Test_execute_function(script, super, self, "__teardown__")))
 {
 if(!quiet)
 printf("<FAILED> function %s() returned error: %d\n","__teardown__", ret);
 VAI(tot_fail)++;
 }
/*
 * Tell how it went
 */
 count = VAI(tot_fail) + VAI(tot_impl) + VAI(tot_success) + VAI(tot_ignored);
 if(count > 0)
 rate = (double)((double)(VAI(tot_success)+VAI(tot_ignored))/ (double)count) * 100;
 else
 rate = 100;
 if(!quiet)
 {
 printf("===================================\n");
 printf("Success rate: %d%%%s\n",rate,(rate!=100)?", test did not pass.":"");
 }
 ffree(iter);
 FE_RETURN_LONG( 100 - rate );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_test_Test___shakedown___ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 259 "test.fec"

 FE_RETURN_LONG( 0 );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_test_Test___misc___ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 263 "test.fec"

 FE_RETURN_LONG( 0 );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_test_Test___setup___ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 251 "test.fec"

 FE_RETURN_LONG( 0 );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

