/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "ipc_header.h"  /* this is the module header */

void ferite_ipc_register()
{
      ferite_module_register_native_function( "IPCObject.read_", ferite_ipc_IPCObject_read_ );
      ferite_module_register_native_function( "IPCObject.disconnect_", ferite_ipc_IPCObject_disconnect_ );
      ferite_module_register_native_function( "IPCObject.write_s", ferite_ipc_IPCObject_write_s );
      ferite_module_register_native_function( "IPCObject.connect_s", ferite_ipc_IPCObject_connect_s );
      ferite_module_register_native_function( "IPCObject.destructor_", ferite_ipc_IPCObject_destructor_ );
      ferite_module_register_native_function( "IPCObject.constructor_n", ferite_ipc_IPCObject_constructor_n );
}

void ferite_ipc_init( FeriteScript *script )
{
}

void ferite_ipc_deinit( FeriteScript *script )
{
}

void ferite_ipc_unregister()
{
}

