/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  date_Date.c */
/* class: Date */

#include <ferite.h>       /* we need this without a doubt */
#include "date_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_date_Date_time_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 125 "date.fec"

 struct tm tm;
 time_t t;
 system_sync_to_tm( self->odata, &tm );
 t = mktime( &tm );
 FE_RETURN_LONG( t );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_toString_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 141 "date.fec"

 FeriteVariable *v;
 struct tm tm;
 system_sync_to_tm( self->odata, &tm );
 v = fe_new_str_static( "asctime", asctime( &tm ), 0 , FE_CHARSET_DEFAULT );
 FE_RETURN_VAR( v );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date___RegisterFromPointer___o )
{
   FeriteObject *tm = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &tm );

   { /* Main function body. */
#line 88 "date.fec"

 if(!tm->odata || strcmp( tm->name, "struct::tm" ) != 0)
 {
 FE_RETURN_FALSE;
 }
 system_sync_to_FeTm( self->odata, tm->odata );
 FE_RETURN_TRUE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_format_s )
{
   FeriteString *fmt = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &fmt );

   { /* Main function body. */
#line 293 "date.fec"

 struct tm tm;
 char *str = NULL;
 int length;
 FeriteVariable *v = NULL;
 length = ((fmt->length * 2) < 100) ? 100 : fmt->length * 2;
 str = fmalloc( length );
 memset( &tm, '\0', sizeof(struct tm) );
 system_sync_to_tm( self->odata, &tm );
 strftime( str, length, fmt->data, &tm );
 v = fe_new_str_static( "strftime", str, 0, FE_CHARSET_DEFAULT );
 ffree( str );
 FE_RETURN_VAR( v );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_destructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 83 "date.fec"

 if( self->odata )
 ffree( self->odata );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 62 "date.fec"

 struct FeTm *Tm = NULL;
 struct tm *tm = NULL;
 self->odata = Tm = fmalloc( sizeof( struct FeTm ) );
 Tm->tm_sec = ferite_object_get_var(script,self,"tm_sec");
 Tm->tm_min = ferite_object_get_var(script,self,"tm_min");
 Tm->tm_hour = ferite_object_get_var(script,self,"tm_hour");
 Tm->tm_mday = ferite_object_get_var(script,self,"tm_mday");
 Tm->tm_mon = ferite_object_get_var(script,self,"tm_mon");
 Tm->tm_year = ferite_object_get_var(script,self,"tm_year");
 Tm->tm_wday = ferite_object_get_var(script,self,"tm_wday");
 Tm->tm_yday = ferite_object_get_var(script,self,"tm_yday");
 Tm->tm_isdst = ferite_object_get_var(script,self,"tm_isdst");
 Tm->tm_zone = ferite_object_get_var(script,self,"tm_zone");
 Tm->tm_gmtoff = ferite_object_get_var(script,self,"tm_gmtoff");
 tm = fcalloc( 1, sizeof(struct tm) );
 memset( tm, '\0', sizeof(struct tm) );
 system_sync_to_FeTm( Tm, tm );
 ffree( tm );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_localParse_ss )
{
   FeriteString *str = NULL;
   FeriteString *fmt = NULL;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 2, &str, &fmt );

   { /* Main function body. */
#line 369 "date.fec"

 
 time_t s = time(NULL);
 struct tm tm = *(localtime(&s));
 strptime( str->data, fmt->data, &tm );
 FE_RETURN_VAR( system_call_tm( script, &tm ) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_now_ )
{
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   { /* Main function body. */
#line 104 "date.fec"

 FE_RETURN_LONG( time(NULL) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_date_n )
{
   double time = 0.0;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 1, &time );

   { /* Main function body. */
#line 317 "date.fec"

 
 struct tm *tm;
 time_t t;
 t = (time_t)time;
 tm = gmtime( &t );
 FE_RETURN_VAR( system_call_tm( script, tm ) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_parse_ss )
{
   FeriteString *str = NULL;
   FeriteString *fmt = NULL;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 2, &str, &fmt );

   { /* Main function body. */
#line 353 "date.fec"

 
 time_t s = time(NULL);
 struct tm tm = *(gmtime(&s));
 strptime( str->data, fmt->data, &tm );
 FE_RETURN_VAR( system_call_tm( script, &tm ) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_timezone_ )
{
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   { /* Main function body. */
#line 384 "date.fec"

#if !defined(USING_SOLARIS) && !defined(USING_CYGWIN) && !defined(USING_MINGW)
 time_t t = time(NULL);
 struct tm *tm = NULL;
 tm = localtime(&t);
 FE_RETURN_LONG( tm->tm_gmtoff );
#else
 FE_RETURN_LONG( 0 );
#endif
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Date_localDate_n )
{
   double timestamp = 0.0;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 1, &timestamp );

   { /* Main function body. */
#line 336 "date.fec"

 
 struct tm *tm = NULL;
 time_t t;
 t = (time_t)timestamp;
 tm = localtime( &t );
 FE_RETURN_VAR( system_call_tm( script, tm ) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

