/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __date_HEADER__
#define __date_HEADER__

#include <ferite.h>

FERITE_API void ferite_date_register();
FERITE_API void ferite_date_unregister();
FERITE_API void ferite_date_init( FeriteScript *script );
FERITE_API void ferite_date_deinit( FeriteScript *script );

    /* Start user defined header code */
 
#include "../../config.h"
#include "util_date.h"

#ifdef WIN32
	char *strptime (const char *buf, const char *format, struct tm *timeptr);
#endif

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_date_Date_time_ );
FE_NATIVE_FUNCTION( ferite_date_Date_toString_ );
FE_NATIVE_FUNCTION( ferite_date_Date___RegisterFromPointer___o );
FE_NATIVE_FUNCTION( ferite_date_Date_format_s );
FE_NATIVE_FUNCTION( ferite_date_Date_destructor_ );
FE_NATIVE_FUNCTION( ferite_date_Date_constructor_ );
FE_NATIVE_FUNCTION( ferite_date_Date_localParse_ss );
FE_NATIVE_FUNCTION( ferite_date_Date_now_ );
FE_NATIVE_FUNCTION( ferite_date_Date_date_n );
FE_NATIVE_FUNCTION( ferite_date_Date_parse_ss );
FE_NATIVE_FUNCTION( ferite_date_Date_timezone_ );
FE_NATIVE_FUNCTION( ferite_date_Date_localDate_n );
FE_NATIVE_FUNCTION( ferite_date_Alarm_stop_ );
FE_NATIVE_FUNCTION( ferite_date_Alarm_start_ );
FE_NATIVE_FUNCTION( ferite_date_Alarm_destructor_ );
FE_NATIVE_FUNCTION( ferite_date_Alarm_constructor_snn );

#endif /* __date_HEADER__ */
