/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  date_Alarm.c */
/* class: Alarm */

#include <ferite.h>       /* we need this without a doubt */
#include "date_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_date_Alarm_stop_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 461 "date.fec"

 
#ifndef WIN32
 AlarmData *alrm = self->odata;
 alarm(0);
 alrm->timeleft = 0;
#endif
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Alarm_start_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 444 "date.fec"

 
#ifndef WIN32
 AlarmData *alrm = self->odata;
 if( signal( SIGALRM, timer_sig_alarm ) == SIG_ERR )
 {
 ferite_error( script, 0, "Couldn't set up alarm signal for timer.");
 }
 else
 alarm( alrm->interval );
#endif
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Alarm_destructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 432 "date.fec"

#ifndef WIN32
 alarm( 0 );
	if( self->odata )
 ffree( self->odata );
#endif
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_date_Alarm_constructor_snn )
{
   FeriteString *functionName = NULL;
   double interval = 0.0;
   double recurring = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 3, &functionName, &interval, &recurring );

   { /* Main function body. */
#line 415 "date.fec"

#ifndef WIN32
 FeriteFunction *func;
 AlarmData *alrm;
 func = ferite_function_get( script, functionName->data );
 self->odata = alrm = fmalloc(sizeof(AlarmData));
 alrm->script = script;
 alrm->function = func;
 alrm->interval = (long)interval;
 alrm->recurring = (long)recurring;
 alrm->timeleft = 0;
 currentAlarm = alrm;
#else
	FE_RETURN_NULL_OBJECT;
#endif
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

