/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "date_header.h"  /* this is the module header */

void ferite_date_register()
{
      ferite_module_register_native_function( "Date.time_", ferite_date_Date_time_ );
      ferite_module_register_native_function( "Date.toString_", ferite_date_Date_toString_ );
      ferite_module_register_native_function( "Date.__RegisterFromPointer___o", ferite_date_Date___RegisterFromPointer___o );
      ferite_module_register_native_function( "Date.format_s", ferite_date_Date_format_s );
      ferite_module_register_native_function( "Date.destructor_", ferite_date_Date_destructor_ );
      ferite_module_register_native_function( "Date.constructor_", ferite_date_Date_constructor_ );
      ferite_module_register_native_function( "Date.localParse_ss", ferite_date_Date_localParse_ss );
      ferite_module_register_native_function( "Date.now_", ferite_date_Date_now_ );
      ferite_module_register_native_function( "Date.date_n", ferite_date_Date_date_n );
      ferite_module_register_native_function( "Date.parse_ss", ferite_date_Date_parse_ss );
      ferite_module_register_native_function( "Date.timezone_", ferite_date_Date_timezone_ );
      ferite_module_register_native_function( "Date.localDate_n", ferite_date_Date_localDate_n );
      ferite_module_register_native_function( "Alarm.stop_", ferite_date_Alarm_stop_ );
      ferite_module_register_native_function( "Alarm.start_", ferite_date_Alarm_start_ );
      ferite_module_register_native_function( "Alarm.destructor_", ferite_date_Alarm_destructor_ );
      ferite_module_register_native_function( "Alarm.constructor_snn", ferite_date_Alarm_constructor_snn );
}

void ferite_date_init( FeriteScript *script )
{
}

void ferite_date_deinit( FeriteScript *script )
{
}

void ferite_date_unregister()
{
}

