/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __sys_HEADER__
#define __sys_HEADER__

#include <ferite.h>

FERITE_API void ferite_sys_register();
FERITE_API void ferite_sys_unregister();
FERITE_API void ferite_sys_init( FeriteScript *script );
FERITE_API void ferite_sys_deinit( FeriteScript *script );

    /* Start user defined header code */


#include "../../config.h"
#include "../../libs/aphex/include/aphex.h"
#include "../stream/util_stream.h"
 
#ifndef VCWIN32
# include <sys/time.h> 
#ifndef WIN32
# include <sys/wait.h>
#endif
#if defined(USING_DARWIN) || defined(USE_SNOWLEOPARD)
# include <crt_externs.h>
# else
 extern char **environ;
# endif
#endif

#include <locale.h>

 

#ifdef WIN32
#include <windows.h>
#endif


    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_sys_Sys_usleep_n );
FE_NATIVE_FUNCTION( ferite_sys_Sys_getVersion_ );
FE_NATIVE_FUNCTION( ferite_sys_Sys_getBuildDate_ );
FE_NATIVE_FUNCTION( ferite_sys_Sys_env_del_s );
FE_NATIVE_FUNCTION( ferite_sys_Sys_env_read_s );
FE_NATIVE_FUNCTION( ferite_sys_Sys_env_toArray_ );
FE_NATIVE_FUNCTION( ferite_sys_Sys_env_write_ss );
FE_NATIVE_FUNCTION( ferite_sys_Sys_system_s );
FE_NATIVE_FUNCTION( ferite_sys_Sys_timestamp_ );
FE_NATIVE_FUNCTION( ferite_sys_Sys_scriptName_ );
FE_NATIVE_FUNCTION( ferite_sys_Sys_sleep_n );
FE_NATIVE_FUNCTION( ferite_sys_Sys_strerror_n );
FE_NATIVE_FUNCTION( ferite_sys_Sys_setlocale_ns );
FE_NATIVE_FUNCTION( ferite_sys_Sys_warning_s );
FE_NATIVE_FUNCTION( ferite_sys_Sys_gc_ );
FE_NATIVE_FUNCTION( ferite_sys_Sys_exit_n );

#endif /* __sys_HEADER__ */
