/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "sys_header.h"  /* this is the module header */

void ferite_sys_register()
{
      ferite_module_register_native_function( "Sys.usleep_n", ferite_sys_Sys_usleep_n );
      ferite_module_register_native_function( "Sys.getVersion_", ferite_sys_Sys_getVersion_ );
      ferite_module_register_native_function( "Sys.getBuildDate_", ferite_sys_Sys_getBuildDate_ );
      ferite_module_register_native_function( "Sys.env.del_s", ferite_sys_Sys_env_del_s );
      ferite_module_register_native_function( "Sys.env.read_s", ferite_sys_Sys_env_read_s );
      ferite_module_register_native_function( "Sys.env.toArray_", ferite_sys_Sys_env_toArray_ );
      ferite_module_register_native_function( "Sys.env.write_ss", ferite_sys_Sys_env_write_ss );
      ferite_module_register_native_function( "Sys.system_s", ferite_sys_Sys_system_s );
      ferite_module_register_native_function( "Sys.timestamp_", ferite_sys_Sys_timestamp_ );
      ferite_module_register_native_function( "Sys.scriptName_", ferite_sys_Sys_scriptName_ );
      ferite_module_register_native_function( "Sys.sleep_n", ferite_sys_Sys_sleep_n );
      ferite_module_register_native_function( "Sys.strerror_n", ferite_sys_Sys_strerror_n );
      ferite_module_register_native_function( "Sys.setlocale_ns", ferite_sys_Sys_setlocale_ns );
      ferite_module_register_native_function( "Sys.warning_s", ferite_sys_Sys_warning_s );
      ferite_module_register_native_function( "Sys.gc_", ferite_sys_Sys_gc_ );
      ferite_module_register_native_function( "Sys.exit_n", ferite_sys_Sys_exit_n );
}

void ferite_sys_init( FeriteScript *script )
{


	FeriteNamespace *ns = ferite_register_namespace( script, "Sys", script->mainns );
	FeriteVariable *var;
	
	var = ferite_create_number_long_variable( script, "LC_ALL", LC_ALL, FE_STATIC );
	MARK_VARIABLE_AS_FINALSET(var);
	ferite_register_ns_variable( script, ns, "LC_ALL", var );
	
	var = ferite_create_number_long_variable( script, "LC_MESSAGES", LC_MESSAGES, FE_STATIC );
	MARK_VARIABLE_AS_FINALSET(var);
	ferite_register_ns_variable( script, ns, "LC_MESSAGES", var );

	var = ferite_create_number_long_variable( script, "LC_NUMERIC", LC_NUMERIC, FE_STATIC );
	MARK_VARIABLE_AS_FINALSET(var);
	ferite_register_ns_variable( script, ns, "LC_NUMERIC", var );

	var = ferite_create_number_long_variable( script, "LC_TIME", LC_TIME, FE_STATIC );
	MARK_VARIABLE_AS_FINALSET(var);
	ferite_register_ns_variable( script, ns, "LC_TIME", var );
}

void ferite_sys_deinit( FeriteScript *script )
{
}

void ferite_sys_unregister()
{
}

