/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "serialize_header.h"  /* this is the module header */

void ferite_serialize_register()
{
      ferite_module_register_native_function( "Serialize.fromNative_s", ferite_serialize_Serialize_fromNative_s );
      ferite_module_register_native_function( "Serialize.toNative_v", ferite_serialize_Serialize_toNative_v );
      ferite_module_register_native_function( "Serialize.toXML_v", ferite_serialize_Serialize_toXML_v );
}

void ferite_serialize_init( FeriteScript *script )
{
}

void ferite_serialize_deinit( FeriteScript *script )
{
}

void ferite_serialize_unregister()
{
}

