/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __serialize_HEADER__
#define __serialize_HEADER__

#include <ferite.h>

FERITE_API void ferite_serialize_register();
FERITE_API void ferite_serialize_unregister();
FERITE_API void ferite_serialize_init( FeriteScript *script );
FERITE_API void ferite_serialize_deinit( FeriteScript *script );

    /* Start user defined header code */


 #include <stdio.h>
 #include <string.h>
 #include "utility.h"

 #define SERIALIZER_VERSION 3
 #define SE_DEBUG( STR ) // printf( "%sAt: %s: %d: %s", ferite_stroflen(' ', (level*2)), __FILE__, __LINE__, STR )

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_serialize_Serialize_fromNative_s );
FE_NATIVE_FUNCTION( ferite_serialize_Serialize_toNative_v );
FE_NATIVE_FUNCTION( ferite_serialize_Serialize_toXML_v );

#endif /* __serialize_HEADER__ */
