/* This file has been automatically generated by builder part of the ferite distribution */
/* file: filesystem_FileSystem.c */
/* namespace: FileSystem */

#include <ferite.h>       /* we need this without a doubt */
#include "filesystem_header.h"  /* this is the module header */

