/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "filesystem_header.h"  /* this is the module header */

void ferite_filesystem_register()
{
      ferite_module_register_native_function( "Directory.destructor_", ferite_filesystem_Directory_destructor_ );
      ferite_module_register_native_function( "Directory.constructor_s", ferite_filesystem_Directory_constructor_s );
      ferite_module_register_native_function( "Directory.getEntry_", ferite_filesystem_Directory_getEntry_ );
      ferite_module_register_native_function( "Directory.getCurrent_", ferite_filesystem_Directory_getCurrent_ );
      ferite_module_register_native_function( "Directory.name_s", ferite_filesystem_Directory_name_s );
      ferite_module_register_native_function( "Directory.make_sn", ferite_filesystem_Directory_make_sn );
      ferite_module_register_native_function( "Directory.setCurrent_s", ferite_filesystem_Directory_setCurrent_s );
      ferite_module_register_native_function( "File.unlock_", ferite_filesystem_File_unlock_ );
      ferite_module_register_native_function( "File.pos_", ferite_filesystem_File_pos_ );
      ferite_module_register_native_function( "File.length_", ferite_filesystem_File_length_ );
      ferite_module_register_native_function( "File.truncate_n", ferite_filesystem_File_truncate_n );
      ferite_module_register_native_function( "File.lock_nn", ferite_filesystem_File_lock_nn );
      ferite_module_register_native_function( "File.seek_nn", ferite_filesystem_File_seek_nn );
      ferite_module_register_native_function( "File.remove_s", ferite_filesystem_File_remove_s );
      ferite_module_register_native_function( "File.name_s", ferite_filesystem_File_name_s );
      ferite_module_register_native_function( "File.move_ss", ferite_filesystem_File_move_ss );
      ferite_module_register_native_function( "File.__create_sn", ferite_filesystem_File___create_sn );
      ferite_module_register_native_function( "File.__open_sn", ferite_filesystem_File___open_sn );
}

void ferite_filesystem_init( FeriteScript *script )
{
 
 int i;
 FeriteVariable *fv;
 FeriteNamespace *Sysns;
 
#include "consts.h"
 
 Sysns = ferite_register_namespace(script, "FileSystem", script->mainns);
 for(i = 0; *constant_names[i]; i++) {
 fv = ferite_create_number_long_variable(script, constant_names[i], constant_values[i], FE_STATIC);
 MARK_VARIABLE_AS_FINALSET(fv);
 ferite_register_ns_variable(script, Sysns, constant_names[i], fv);
 }
}

void ferite_filesystem_deinit( FeriteScript *script )
{
}

void ferite_filesystem_unregister()
{
}

