/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __filesystem_HEADER__
#define __filesystem_HEADER__

#include <ferite.h>

FERITE_API void ferite_filesystem_register();
FERITE_API void ferite_filesystem_unregister();
FERITE_API void ferite_filesystem_init( FeriteScript *script );
FERITE_API void ferite_filesystem_deinit( FeriteScript *script );

    /* Start user defined header code */


#include "../../config.h"
#include "../../libs/aphex/include/aphex.h"
#include "../stream/util_stream.h"
#ifndef WIN32
#include <dirent.h>
#include <sys/file.h>
#define ENDOFLINE "\n"
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <fcntl.h>
#else
#include <windows.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <io.h>

#define ENDOFLINE "\r\n"
#endif


    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_filesystem_Directory_destructor_ );
FE_NATIVE_FUNCTION( ferite_filesystem_Directory_constructor_s );
FE_NATIVE_FUNCTION( ferite_filesystem_Directory_getEntry_ );
FE_NATIVE_FUNCTION( ferite_filesystem_Directory_getCurrent_ );
FE_NATIVE_FUNCTION( ferite_filesystem_Directory_name_s );
FE_NATIVE_FUNCTION( ferite_filesystem_Directory_make_sn );
FE_NATIVE_FUNCTION( ferite_filesystem_Directory_setCurrent_s );
FE_NATIVE_FUNCTION( ferite_filesystem_File_unlock_ );
FE_NATIVE_FUNCTION( ferite_filesystem_File_pos_ );
FE_NATIVE_FUNCTION( ferite_filesystem_File_length_ );
FE_NATIVE_FUNCTION( ferite_filesystem_File_truncate_n );
FE_NATIVE_FUNCTION( ferite_filesystem_File_lock_nn );
FE_NATIVE_FUNCTION( ferite_filesystem_File_seek_nn );
FE_NATIVE_FUNCTION( ferite_filesystem_File_remove_s );
FE_NATIVE_FUNCTION( ferite_filesystem_File_name_s );
FE_NATIVE_FUNCTION( ferite_filesystem_File_move_ss );
FE_NATIVE_FUNCTION( ferite_filesystem_File___create_sn );
FE_NATIVE_FUNCTION( ferite_filesystem_File___open_sn );

#endif /* __filesystem_HEADER__ */
