/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "string_header.h"  /* this is the module header */

void ferite_string_register()
{
      ferite_module_register_native_function( "String.octalStringToNumber_s", ferite_string_String_octalStringToNumber_s );
      ferite_module_register_native_function( "String.toHex_s", ferite_string_String_toHex_s );
      ferite_module_register_native_function( "String.escape_s", ferite_string_String_escape_s );
      ferite_module_register_native_function( "String.postTrim_ss", ferite_string_String_postTrim_ss );
      ferite_module_register_native_function( "String.trim_ss", ferite_string_String_trim_ss );
      ferite_module_register_native_function( "String.__isfmt_s", ferite_string_String___isfmt_s );
      ferite_module_register_native_function( "String.isprint_s", ferite_string_String_isprint_s );
      ferite_module_register_native_function( "String.isdigit_s", ferite_string_String_isdigit_s );
      ferite_module_register_native_function( "String.isgraph_s", ferite_string_String_isgraph_s );
      ferite_module_register_native_function( "String.toNumber_s", ferite_string_String_toNumber_s );
      ferite_module_register_native_function( "String.base64encode_s", ferite_string_String_base64encode_s );
      ferite_module_register_native_function( "String.compare_ss", ferite_string_String_compare_ss );
      ferite_module_register_native_function( "String.preTrim_ss", ferite_string_String_preTrim_ss );
      ferite_module_register_native_function( "String.blocks_sn", ferite_string_String_blocks_sn );
      ferite_module_register_native_function( "String.toLower_s", ferite_string_String_toLower_s );
      ferite_module_register_native_function( "String.length_s", ferite_string_String_length_s );
      ferite_module_register_native_function( "String.nCompareCase_ssn", ferite_string_String_nCompareCase_ssn );
      ferite_module_register_native_function( "String.toUpper_s", ferite_string_String_toUpper_s );
      ferite_module_register_native_function( "String.nCompareNoCase_ssn", ferite_string_String_nCompareNoCase_ssn );
      ferite_module_register_native_function( "String.byteToNumber_s", ferite_string_String_byteToNumber_s );
      ferite_module_register_native_function( "String.numberToByte_n", ferite_string_String_numberToByte_n );
      ferite_module_register_native_function( "String.toDouble_s", ferite_string_String_toDouble_s );
      ferite_module_register_native_function( "String.hexStringToNumber_s", ferite_string_String_hexStringToNumber_s );
      ferite_module_register_native_function( "String.ispunct_s", ferite_string_String_ispunct_s );
      ferite_module_register_native_function( "String.isalnum_s", ferite_string_String_isalnum_s );
      ferite_module_register_native_function( "String.dissect_ssn", ferite_string_String_dissect_ssn );
      ferite_module_register_native_function( "String.index_ss", ferite_string_String_index_ss );
      ferite_module_register_native_function( "String.pad_sns", ferite_string_String_pad_sns );
      ferite_module_register_native_function( "String.isNumber_s", ferite_string_String_isNumber_s );
      ferite_module_register_native_function( "String.replace_sss", ferite_string_String_replace_sss );
      ferite_module_register_native_function( "String.isalpha_s", ferite_string_String_isalpha_s );
      ferite_module_register_native_function( "String.compareCase_ss", ferite_string_String_compareCase_ss );
      ferite_module_register_native_function( "String.binaryStringToNumber_s", ferite_string_String_binaryStringToNumber_s );
      ferite_module_register_native_function( "String.compareNoCase_ss", ferite_string_String_compareNoCase_ss );
      ferite_module_register_native_function( "String.islower_s", ferite_string_String_islower_s );
      ferite_module_register_native_function( "String.toLong_s", ferite_string_String_toLong_s );
      ferite_module_register_native_function( "String.isupper_s", ferite_string_String_isupper_s );
      ferite_module_register_native_function( "String.orderedCompare_ss", ferite_string_String_orderedCompare_ss );
      ferite_module_register_native_function( "String.iscntrl_s", ferite_string_String_iscntrl_s );
      ferite_module_register_native_function( "String.unescape_s", ferite_string_String_unescape_s );
      ferite_module_register_native_function( "String.__printvar_sv", ferite_string_String___printvar_sv );
      ferite_module_register_native_function( "String.isspace_s", ferite_string_String_isspace_s );
      ferite_module_register_native_function( "String.base64decode_s", ferite_string_String_base64decode_s );
      ferite_module_register_native_function( "String.toArray_ssn", ferite_string_String_toArray_ssn );
      ferite_module_register_native_function( "String.isxdigit_s", ferite_string_String_isxdigit_s );
      ferite_module_register_native_function( "String.hexToNumber_s", ferite_string_String_hexToNumber_s );
}

void ferite_string_init( FeriteScript *script )
{
}

void ferite_string_deinit( FeriteScript *script )
{
}

void ferite_string_unregister()
{
}

