/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  unix_Unix_SyslogStream.c */
/* class: SyslogStream */

#include <ferite.h>       /* we need this without a doubt */
#include "unix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_error_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 303 "syslog.fec"

           StreamObject->file_descriptor = LOG_ERR;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_debug_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 339 "syslog.fec"

           StreamObject->file_descriptor = LOG_DEBUG;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream___read___n )
{
   double count = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &count );

   { /* Main function body. */
#line 350 "syslog.fec"

           ferite_error( script, 0, "The syslog is write only." );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_notice_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 327 "syslog.fec"

           StreamObject->file_descriptor = LOG_NOTICE;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_warning_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 315 "syslog.fec"

           StreamObject->file_descriptor = LOG_WARNING;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_alert_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 279 "syslog.fec"

           StreamObject->file_descriptor = LOG_ALERT;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream___write___s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 345 "syslog.fec"

           syslog(StreamObject->file_descriptor, "%s", s->data);
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_critical_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 291 "syslog.fec"

           StreamObject->file_descriptor = LOG_CRIT;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_info_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 255 "syslog.fec"

           StreamObject->file_descriptor = LOG_INFO;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_emerg_s )
{
   FeriteString *s = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &s );

   { /* Main function body. */
#line 267 "syslog.fec"

           StreamObject->file_descriptor = LOG_EMERG;
           FE_RETURN_VAR(ferite_call_function(script, self, NULL, StreamObject->write, params));
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream___close___ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 355 "syslog.fec"

           closelog();
           struct Stream *Stream = self->odata;
           ffree( Stream->filename );
           Stream->filename = NULL;
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Unix_SyslogStream_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 237 "syslog.fec"

           FeriteVariable *c = ferite_create_object_variable_with_data( script, "SyslogStream", self, FE_STATIC );
           
           ferite_variable_destroy( script, ferite_object_call_super(script, c, NULL) );
           ferite_variable_destroy( script, c );
           
           StreamObject->file_descriptor = LOG_NOTICE;
           StreamObject->read = ferite_object_get_function(script, self, "__read__" );
           StreamObject->write = ferite_object_get_function(script, self, "__write__" );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

