/* This file has been automatically generated by builder part of the ferite distribution */
/* file: unix_Unix.c */
/* namespace: Unix */

#include <ferite.h>       /* we need this without a doubt */
#include "unix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_unix_Unix_openlog_snn )
{
   FeriteString *ident = NULL;
   double option = 0.0;
   double facility = 0.0;
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 3, &ident, &option, &facility );

   { /* Main function body. */
#line 216 "syslog.fec"

        FeriteClass *cls;
        FeriteVariable *obj;

        if((cls = ferite_find_class( script, script->mainns, "Unix.SyslogStream"))) {
            obj = ferite_new_object(script, cls, NULL);
            struct Stream *Stream = VAO(obj)->odata;
            Stream->filename = fstrdup( ident->data );
            openlog(Stream->filename, (int)option, (int)facility);
            FE_RETURN_VAR(obj);
        }
    
   }
   FE_RETURN_VOID;
   self = NULL;
}

