/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  unix_Closure.c */
/* class: Closure */

#include <ferite.h>       /* we need this without a doubt */
#include "unix_header.h"  /* this is the module header */

