/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "unix_header.h"  /* this is the module header */

void ferite_unix_register()
{
      ferite_module_register_native_function( "Unix.SyslogStream.error_s", ferite_unix_Unix_SyslogStream_error_s );
      ferite_module_register_native_function( "Unix.SyslogStream.debug_s", ferite_unix_Unix_SyslogStream_debug_s );
      ferite_module_register_native_function( "Unix.SyslogStream.__read___n", ferite_unix_Unix_SyslogStream___read___n );
      ferite_module_register_native_function( "Unix.SyslogStream.notice_s", ferite_unix_Unix_SyslogStream_notice_s );
      ferite_module_register_native_function( "Unix.SyslogStream.warning_s", ferite_unix_Unix_SyslogStream_warning_s );
      ferite_module_register_native_function( "Unix.SyslogStream.alert_s", ferite_unix_Unix_SyslogStream_alert_s );
      ferite_module_register_native_function( "Unix.SyslogStream.__write___s", ferite_unix_Unix_SyslogStream___write___s );
      ferite_module_register_native_function( "Unix.SyslogStream.critical_s", ferite_unix_Unix_SyslogStream_critical_s );
      ferite_module_register_native_function( "Unix.SyslogStream.info_s", ferite_unix_Unix_SyslogStream_info_s );
      ferite_module_register_native_function( "Unix.SyslogStream.emerg_s", ferite_unix_Unix_SyslogStream_emerg_s );
      ferite_module_register_native_function( "Unix.SyslogStream.__close___", ferite_unix_Unix_SyslogStream___close___ );
      ferite_module_register_native_function( "Unix.SyslogStream.constructor_", ferite_unix_Unix_SyslogStream_constructor_ );
      ferite_module_register_native_function( "Unix.openlog_snn", ferite_unix_Unix_openlog_snn );
      ferite_module_register_native_function( "Network.Unix.Stream.listen_n", ferite_unix_Network_Unix_Stream_listen_n );
      ferite_module_register_native_function( "Network.Unix.Stream.accept_", ferite_unix_Network_Unix_Stream_accept_ );
      ferite_module_register_native_function( "Network.Unix.connect_s", ferite_unix_Network_Unix_connect_s );
      ferite_module_register_native_function( "Network.Unix.bind_s", ferite_unix_Network_Unix_bind_s );
}

void ferite_unix_init( FeriteScript *script )
{
 
 int i;
 FeriteVariable *fv;
 FeriteNamespace *Sysns;
 
#include "consts.h"
 
 Sysns = ferite_register_namespace(script, "Unix", script->mainns);
 for(i = 0; *constant_names[i]; i++) {
 fv = ferite_create_number_long_variable(script, constant_names[i], constant_values[i], FE_STATIC);
 MARK_VARIABLE_AS_FINALSET(fv);
 ferite_register_ns_variable(script, Sysns, constant_names[i], fv);
 }
}

void ferite_unix_deinit( FeriteScript *script )
{
}

void ferite_unix_unregister()
{
}

