/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  unix_Network_Unix_Stream.c */
/* class: Stream */

#include <ferite.h>       /* we need this without a doubt */
#include "unix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_unix_Network_Unix_Stream_listen_n )
{
   double backlog = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &backlog );

   { /* Main function body. */
#line 108 "unixsocket.fec"

 int sock = StreamObject->file_descriptor;
 int retval = listen(sock, (long)backlog);
 FE_RETURN_LONG(retval);
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_unix_Network_Unix_Stream_accept_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 68 "unixsocket.fec"

 FeriteVariable *obj, **args, *fv;
 FeriteClass *cls;
 int sock;
 
 do
 {
 sock = accept(StreamObject->file_descriptor, NULL, NULL);
 }
 while(sock == -1 && errno == EINTR);
 
 if(sock == -1)
 {
 ferite_set_error(script, errno, "%s", strerror(errno));
 FE_RETURN_NULL_OBJECT;
 }
 
 if((cls = ferite_find_class(script, script->mainns, "Network.Unix.Stream")))
 {
 args = ferite_create_parameter_list(script,4);
 args = ferite_add_to_parameter_list(args, fe_new_lng_static("socket", sock));
 MARK_VARIABLE_AS_DISPOSABLE(args[0]);
 obj = ferite_new_object(script, cls, args);
 ferite_delete_parameter_list(script, args);
 fv = ferite_object_get_var(script, self, "path");
 fv = ferite_create_string_variable(script, "path", VAS(fv),
 FE_STATIC);
 ferite_object_set_var(script, VAO(obj), "path", fv);
 FE_RETURN_VAR(obj);
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

