/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  math_Math_Complex.c */
/* class: Complex */

#include <ferite.h>       /* we need this without a doubt */
#include "math_header.h"  /* this is the module header */

