/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "math_header.h"  /* this is the module header */

void ferite_math_register()
{
      ferite_module_register_native_function( "Math.max_nn", ferite_math_Math_max_nn );
      ferite_module_register_native_function( "Math.rand_", ferite_math_Math_rand_ );
      ferite_module_register_native_function( "Math.getRandMax_", ferite_math_Math_getRandMax_ );
      ferite_module_register_native_function( "Math.min_nn", ferite_math_Math_min_nn );
      ferite_module_register_native_function( "Math.srand_n", ferite_math_Math_srand_n );
      ferite_module_register_native_function( "Math.pi_", ferite_math_Math_pi_ );
}

void ferite_math_init( FeriteScript *script )
{
}

void ferite_math_deinit( FeriteScript *script )
{
}

void ferite_math_unregister()
{
}

