/* This file has been automatically generated by builder part of the ferite distribution */
/* file: math_Math.c */
/* namespace: Math */

#include <ferite.h>       /* we need this without a doubt */
#include "math_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_math_Math_max_nn )
{
   double num1 = 0.0;
   double num2 = 0.0;
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 2, &num1, &num2 );

   { /* Main function body. */
#line 71 "math.fec"

	if( num1 < num2 )
	{
	FE_RETURN_DOUBLE( num2 );
	}
	else
	{
	FE_RETURN_DOUBLE( num1 );
	}
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_math_Math_rand_ )
{
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   { /* Main function body. */
#line 124 "math.fec"

	FE_RETURN_LONG( rand() );
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_math_Math_getRandMax_ )
{
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   { /* Main function body. */
#line 58 "math.fec"

	FE_RETURN_LONG( RAND_MAX );
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_math_Math_min_nn )
{
   double num1 = 0.0;
   double num2 = 0.0;
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 2, &num1, &num2 );

   { /* Main function body. */
#line 91 "math.fec"

	if( num1 > num2 )
	{
	FE_RETURN_DOUBLE( num2 );
	}
	else
	{
	FE_RETURN_DOUBLE( num1 );
	}
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_math_Math_srand_n )
{
   double seed = 0.0;
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 1, &seed );

   { /* Main function body. */
#line 144 "math.fec"

	
	srand( (long)seed );
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_math_Math_pi_ )
{
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   { /* Main function body. */
#line 109 "math.fec"

	FE_RETURN_DOUBLE( M_PI );
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

