/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __math_HEADER__
#define __math_HEADER__

#include <ferite.h>

FERITE_API void ferite_math_register();
FERITE_API void ferite_math_unregister();
FERITE_API void ferite_math_init( FeriteScript *script );
FERITE_API void ferite_math_deinit( FeriteScript *script );

    /* Start user defined header code */



#include <math.h>
#include <stdlib.h>
#ifndef M_PI
# define M_PI 3.14159265358979323846
#endif


    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_math_Math_max_nn );
FE_NATIVE_FUNCTION( ferite_math_Math_rand_ );
FE_NATIVE_FUNCTION( ferite_math_Math_getRandMax_ );
FE_NATIVE_FUNCTION( ferite_math_Math_min_nn );
FE_NATIVE_FUNCTION( ferite_math_Math_srand_n );
FE_NATIVE_FUNCTION( ferite_math_Math_pi_ );

#endif /* __math_HEADER__ */
