/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  posix_Posix_Pipe.c */
/* class: Pipe */

#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_posix_Posix_Pipe_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 538 "posix.fec"

 FeriteVariable *sin, *sout;
 int fds[2];
 FILE *in, *out;
 if(pipe(fds) == -1) FE_RETURN_NULL_OBJECT;
 if(!(out = fdopen(fds[0], "r")))
 {
 close(fds[0]);
 close(fds[1]);
 FE_RETURN_NULL_OBJECT;
 }
 if(!(in = fdopen(fds[1], "w")))
 {
 fclose(out);
 close(fds[1]);
 FE_RETURN_NULL_OBJECT;
 }
 setvbuf(in, NULL, _IONBF, 0);
 sin = system_create_stream_object(script, "Stream.StdioStream", in);
 sout = system_create_stream_object(script, "Stream.StdioStream", out);
 ferite_object_set_var(script, self, "in", sin);
 ferite_object_set_var(script, self, "out", sout);
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

