/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  posix_Posix_Stat.c */
/* class: Stat */

#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isLink_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 318 "posix.fec"

 FE_RETURN_BOOL( S_ISLNK(SelfStat->st_mode) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getAccessTime_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 409 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_atime );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSuid_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 348 "posix.fec"

 FE_RETURN_BOOL( SelfStat->st_mode & S_ISUID );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isFifo_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 308 "posix.fec"

 FE_RETURN_BOOL( S_ISFIFO(SelfStat->st_mode) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isCharDevice_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 278 "posix.fec"

 FE_RETURN_BOOL( S_ISCHR(SelfStat->st_mode) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getOwnerID_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 389 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_uid );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isDirectory_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 265 "posix.fec"

	if( S_ISDIR(SelfStat->st_mode) ) {
	FE_RETURN_TRUE;
	}
	FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getGroupID_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 399 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_gid );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getChangedTime_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 419 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_ctime );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getModifiedTime_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 429 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_mtime );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isRegularFile_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 288 "posix.fec"

 FE_RETURN_BOOL( S_ISREG(SelfStat->st_mode) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSticky_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 338 "posix.fec"

           FE_RETURN_BOOL( SelfStat->st_mode & S_ISVTX );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getInode_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 379 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_ino );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getSize_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 369 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_size );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getBlockCount_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 449 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_blocks );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getBlockSize_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 439 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_blksize );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSgid_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 358 "posix.fec"

           FE_RETURN_BOOL( SelfStat->st_mode & S_ISGID );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isBlockDevice_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 298 "posix.fec"

 FE_RETURN_BOOL( S_ISBLK(SelfStat->st_mode) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_destructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 254 "posix.fec"

 if( self->odata )
 ffree( self->odata );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_constructor_o )
{
   FeriteObject *stat = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &stat );

   { /* Main function body. */
#line 219 "posix.fec"

 struct stat *in;
 FeriteVariable *v;
 if(!stat->odata || strcmp( stat->name, "struct::stat" ) != 0)
 FE_RETURN_VOID;
 in = self->odata = stat->odata;
 v = ferite_object_get_var(script,self,"st_dev");
 VAI(v) = in->st_dev;
 v = ferite_object_get_var(script,self,"st_ino");
 VAI(v) = in->st_ino;
 v = ferite_object_get_var(script,self,"st_mode");
 VAI(v) = in->st_mode;
 v = ferite_object_get_var(script,self,"st_nlink");
 VAI(v) = in->st_nlink;
 v = ferite_object_get_var(script,self,"st_uid");
 VAI(v) = in->st_uid;
 v = ferite_object_get_var(script,self,"st_gid");
 VAI(v) = in->st_gid;
 v = ferite_object_get_var(script,self,"st_rdev");
 VAI(v) = in->st_rdev;
 v = ferite_object_get_var(script,self,"st_size");
 VAI(v) = in->st_size;
 v = ferite_object_get_var(script,self,"st_blksize");
 VAI(v) = in->st_blksize;
 v = ferite_object_get_var(script,self,"st_blocks");
 VAI(v) = in->st_blocks;
 v = ferite_object_get_var(script,self,"st_atime");
 VAI(v) = in->st_atime;
 v = ferite_object_get_var(script,self,"st_mtime");
 VAI(v) = in->st_mtime;
 v = ferite_object_get_var(script,self,"st_ctime");
 VAI(v) = in->st_ctime;

 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSocket_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 328 "posix.fec"

 FE_RETURN_BOOL( S_ISSOCK(SelfStat->st_mode) );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getLinkCount_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 459 "posix.fec"

           FE_RETURN_LONG( SelfStat->st_nlink );
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

