/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  posix_Posix_Uname.c */
/* class: Uname */

#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_posix_Posix_Uname_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 492 "posix.fec"

 FeriteVariable *fv;
 struct utsname u;

 uname(&u);
 fv = ferite_create_string_variable_from_ptr(script, "sysname",
 u.sysname, 0, FE_CHARSET_DEFAULT, FE_STATIC);
 ferite_object_set_var(script, self, "sysname", fv);
 fv = ferite_create_string_variable_from_ptr(script, "release",
 u.release, 0, FE_CHARSET_DEFAULT, FE_STATIC);
 ferite_object_set_var(script, self, "release", fv);
 fv = ferite_create_string_variable_from_ptr(script, "version",
 u.version, 0, FE_CHARSET_DEFAULT, FE_STATIC);
 ferite_object_set_var(script, self, "version", fv);
 fv = ferite_create_string_variable_from_ptr(script, "machine",
 u.machine, 0, FE_CHARSET_DEFAULT, FE_STATIC);
 ferite_object_set_var(script, self, "machine", fv);
 fv = ferite_create_string_variable_from_ptr(script, "nodename",
 u.nodename, 0, FE_CHARSET_DEFAULT, FE_STATIC);
 ferite_object_set_var(script, self, "nodename", fv);
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

