/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  posix_Posix_SelectResult.c */
/* class: SelectResult */

#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

