/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  posix_Posix_User.c */
/* class: User */

#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_posix_Posix_User_constructor_n )
{
   double uid = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &uid );

   { /* Main function body. */
#line 1048 "posix.fec"

 struct passwd *pw;
 pw = getpwuid((uid_t)uid);
 system_sync_pwent_to_self( script, self, pw );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

