/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

void ferite_posix_register()
{
      ferite_module_register_native_function( "Posix.setgid_n", ferite_posix_Posix_setgid_n );
      ferite_module_register_native_function( "Posix.lstat_s", ferite_posix_Posix_lstat_s );
      ferite_module_register_native_function( "Posix.Uname.constructor_", ferite_posix_Posix_Uname_constructor_ );
      ferite_module_register_native_function( "Posix.geteuid_", ferite_posix_Posix_geteuid_ );
      ferite_module_register_native_function( "Posix.chown_snn", ferite_posix_Posix_chown_snn );
      ferite_module_register_native_function( "Posix.umask_n", ferite_posix_Posix_umask_n );
      ferite_module_register_native_function( "Posix.fork_", ferite_posix_Posix_fork_ );
      ferite_module_register_native_function( "Posix.utime_s", ferite_posix_Posix_utime_s );
      ferite_module_register_native_function( "Posix.utime_snn", ferite_posix_Posix_utime_snn );
      ferite_module_register_native_function( "Posix.softlink_ss", ferite_posix_Posix_softlink_ss );
      ferite_module_register_native_function( "Posix.access_ss", ferite_posix_Posix_access_ss );
      ferite_module_register_native_function( "Posix.hardlink_ss", ferite_posix_Posix_hardlink_ss );
      ferite_module_register_native_function( "Posix.openprocess_ss", ferite_posix_Posix_openprocess_ss );
      ferite_module_register_native_function( "Posix.setPriority_nnn", ferite_posix_Posix_setPriority_nnn );
      ferite_module_register_native_function( "Posix.chroot_s", ferite_posix_Posix_chroot_s );
      ferite_module_register_native_function( "Posix.Rlimit.set_", ferite_posix_Posix_Rlimit_set_ );
      ferite_module_register_native_function( "Posix.Rlimit.constructor_n", ferite_posix_Posix_Rlimit_constructor_n );
      ferite_module_register_native_function( "Posix.mkfifo_sn", ferite_posix_Posix_mkfifo_sn );
      ferite_module_register_native_function( "Posix.User.constructor_n", ferite_posix_Posix_User_constructor_n );
      ferite_module_register_native_function( "Posix.setsid_", ferite_posix_Posix_setsid_ );
      ferite_module_register_native_function( "Posix.getgid_", ferite_posix_Posix_getgid_ );
      ferite_module_register_native_function( "Posix.setuid_n", ferite_posix_Posix_setuid_n );
      ferite_module_register_native_function( "Posix.Pipe.constructor_", ferite_posix_Posix_Pipe_constructor_ );
      ferite_module_register_native_function( "Posix.Rusage.constructor_n", ferite_posix_Posix_Rusage_constructor_n );
      ferite_module_register_native_function( "Posix.ProcessStream.eos_", ferite_posix_Posix_ProcessStream_eos_ );
      ferite_module_register_native_function( "Posix.ProcessStream.__read___n", ferite_posix_Posix_ProcessStream___read___n );
      ferite_module_register_native_function( "Posix.ProcessStream.__write___s", ferite_posix_Posix_ProcessStream___write___s );
      ferite_module_register_native_function( "Posix.ProcessStream.__close___", ferite_posix_Posix_ProcessStream___close___ );
      ferite_module_register_native_function( "Posix.ProcessStream.constructor_o", ferite_posix_Posix_ProcessStream_constructor_o );
      ferite_module_register_native_function( "Posix.exec_saa", ferite_posix_Posix_exec_saa );
      ferite_module_register_native_function( "Posix.getppid_", ferite_posix_Posix_getppid_ );
      ferite_module_register_native_function( "Posix.getegid_", ferite_posix_Posix_getegid_ );
      ferite_module_register_native_function( "Posix.stat_s", ferite_posix_Posix_stat_s );
      ferite_module_register_native_function( "Posix.Stat.isLink_", ferite_posix_Posix_Stat_isLink_ );
      ferite_module_register_native_function( "Posix.Stat.getAccessTime_", ferite_posix_Posix_Stat_getAccessTime_ );
      ferite_module_register_native_function( "Posix.Stat.isSuid_", ferite_posix_Posix_Stat_isSuid_ );
      ferite_module_register_native_function( "Posix.Stat.isFifo_", ferite_posix_Posix_Stat_isFifo_ );
      ferite_module_register_native_function( "Posix.Stat.isCharDevice_", ferite_posix_Posix_Stat_isCharDevice_ );
      ferite_module_register_native_function( "Posix.Stat.getOwnerID_", ferite_posix_Posix_Stat_getOwnerID_ );
      ferite_module_register_native_function( "Posix.Stat.isDirectory_", ferite_posix_Posix_Stat_isDirectory_ );
      ferite_module_register_native_function( "Posix.Stat.getGroupID_", ferite_posix_Posix_Stat_getGroupID_ );
      ferite_module_register_native_function( "Posix.Stat.getChangedTime_", ferite_posix_Posix_Stat_getChangedTime_ );
      ferite_module_register_native_function( "Posix.Stat.getModifiedTime_", ferite_posix_Posix_Stat_getModifiedTime_ );
      ferite_module_register_native_function( "Posix.Stat.isRegularFile_", ferite_posix_Posix_Stat_isRegularFile_ );
      ferite_module_register_native_function( "Posix.Stat.isSticky_", ferite_posix_Posix_Stat_isSticky_ );
      ferite_module_register_native_function( "Posix.Stat.getInode_", ferite_posix_Posix_Stat_getInode_ );
      ferite_module_register_native_function( "Posix.Stat.getSize_", ferite_posix_Posix_Stat_getSize_ );
      ferite_module_register_native_function( "Posix.Stat.getBlockCount_", ferite_posix_Posix_Stat_getBlockCount_ );
      ferite_module_register_native_function( "Posix.Stat.getBlockSize_", ferite_posix_Posix_Stat_getBlockSize_ );
      ferite_module_register_native_function( "Posix.Stat.isSgid_", ferite_posix_Posix_Stat_isSgid_ );
      ferite_module_register_native_function( "Posix.Stat.isBlockDevice_", ferite_posix_Posix_Stat_isBlockDevice_ );
      ferite_module_register_native_function( "Posix.Stat.destructor_", ferite_posix_Posix_Stat_destructor_ );
      ferite_module_register_native_function( "Posix.Stat.constructor_o", ferite_posix_Posix_Stat_constructor_o );
      ferite_module_register_native_function( "Posix.Stat.isSocket_", ferite_posix_Posix_Stat_isSocket_ );
      ferite_module_register_native_function( "Posix.Stat.getLinkCount_", ferite_posix_Posix_Stat_getLinkCount_ );
      ferite_module_register_native_function( "Posix.getpid_", ferite_posix_Posix_getpid_ );
      ferite_module_register_native_function( "Posix.waitpid_nn", ferite_posix_Posix_waitpid_nn );
      ferite_module_register_native_function( "Posix.resetSigAction_n", ferite_posix_Posix_resetSigAction_n );
      ferite_module_register_native_function( "Posix.getPriority_nn", ferite_posix_Posix_getPriority_nn );
      ferite_module_register_native_function( "Posix.ignoreSignal_n", ferite_posix_Posix_ignoreSignal_n );
      ferite_module_register_native_function( "Posix.getuid_", ferite_posix_Posix_getuid_ );
      ferite_module_register_native_function( "Posix.select_aaan", ferite_posix_Posix_select_aaan );
      ferite_module_register_native_function( "Posix.registerSigHandler_nso", ferite_posix_Posix_registerSigHandler_nso );
      ferite_module_register_native_function( "Posix.chmod_sn", ferite_posix_Posix_chmod_sn );
      ferite_module_register_native_function( "Posix.kill_nn", ferite_posix_Posix_kill_nn );
    /* Start user defined register code */
 
 ferite_signal_init();

    /* End user defined register code */
}

void ferite_posix_init( FeriteScript *script )
{
 
 int i;
 FeriteVariable *fv;
 FeriteNamespace *Sysns;

#include "consts.h"

 Sysns = ferite_register_namespace(script, "Posix", script->mainns);
 for(i = 0; *constant_names[i]; i++) {
 fv = ferite_create_number_long_variable(script, constant_names[i], constant_values[i], FE_STATIC);
 MARK_VARIABLE_AS_FINALSET(fv);
 ferite_register_ns_variable(script, Sysns, constant_names[i], fv);
 }
}

void ferite_posix_deinit( FeriteScript *script )
{
    /* Start user defined deinitialisation code */
 
 ferite_signal_remove_script( script );

    /* End user defined deinitialisation code */
}

void ferite_posix_unregister()
{
    /* Start user defined unregister code */
 
 ferite_signal_deinit();

    /* End user defined unregister code */
}

