/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  posix_Posix_Rusage.c */
/* class: Rusage */

#include <ferite.h>       /* we need this without a doubt */
#include "posix_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_posix_Posix_Rusage_constructor_n )
{
   double getchild = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &getchild );

   { /* Main function body. */
#line 1408 "posix.fec"

           FeriteVariable *fv;
           struct rusage r;

           if((int)getchild) getrusage(RUSAGE_CHILDREN, &r);
           else getrusage(RUSAGE_SELF, &r);

           fv = ferite_object_get_var(script, self, "utime");
           F_VAR_TYPE(fv) = F_VAR_DOUBLE;
           VAF(fv) = r.ru_utime.tv_sec + (double)((double)r.ru_utime.tv_usec /
                                                  1000000);
           fv = ferite_object_get_var(script, self, "stime");
           F_VAR_TYPE(fv) = F_VAR_DOUBLE;
           VAF(fv) = r.ru_stime.tv_sec + (double)((double)r.ru_stime.tv_usec /
                                                  1000000);
           fv = ferite_object_get_var(script, self, "maxrss");
           VAI(fv) = r.ru_maxrss;
           fv = ferite_object_get_var(script, self, "ixrss");
           VAI(fv) = r.ru_ixrss;
           fv = ferite_object_get_var(script, self, "idrss");
           VAI(fv) = r.ru_idrss;
           fv = ferite_object_get_var(script, self, "isrss");
           VAI(fv) = r.ru_isrss;
           fv = ferite_object_get_var(script, self, "minflt");
           VAI(fv) = r.ru_minflt;
           fv = ferite_object_get_var(script, self, "majflt");
           VAI(fv) = r.ru_majflt;
           fv = ferite_object_get_var(script, self, "nswap");
           VAI(fv) = r.ru_nswap;
           fv = ferite_object_get_var(script, self, "inblock");
           VAI(fv) = r.ru_inblock;
           fv = ferite_object_get_var(script, self, "oublock");
           VAI(fv) = r.ru_oublock;
           fv = ferite_object_get_var(script, self, "msgsnd");
           VAI(fv) = r.ru_msgsnd;
           fv = ferite_object_get_var(script, self, "msgrcv");
           VAI(fv) = r.ru_msgrcv;
           fv = ferite_object_get_var(script, self, "nsignals");
           VAI(fv) = r.ru_nsignals;
           fv = ferite_object_get_var(script, self, "nvcsw");
           VAI(fv) = r.ru_nvcsw;
           fv = ferite_object_get_var(script, self, "nivcsw");
           VAI(fv) = r.ru_nivcsw;
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

