/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __posix_HEADER__
#define __posix_HEADER__

#include <ferite.h>

FERITE_API void ferite_posix_register();
FERITE_API void ferite_posix_unregister();
FERITE_API void ferite_posix_init( FeriteScript *script );
FERITE_API void ferite_posix_deinit( FeriteScript *script );

    /* Start user defined header code */
 
#include "util_posix.h"
#include "util_signal.h"
#include "util_user.h"
#include "../stream/util_stream.h"

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_posix_Posix_setgid_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_lstat_s );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Uname_constructor_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_geteuid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_chown_snn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_umask_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_fork_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_utime_s );
FE_NATIVE_FUNCTION( ferite_posix_Posix_utime_snn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_softlink_ss );
FE_NATIVE_FUNCTION( ferite_posix_Posix_access_ss );
FE_NATIVE_FUNCTION( ferite_posix_Posix_hardlink_ss );
FE_NATIVE_FUNCTION( ferite_posix_Posix_openprocess_ss );
FE_NATIVE_FUNCTION( ferite_posix_Posix_setPriority_nnn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_chroot_s );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Rlimit_set_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Rlimit_constructor_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_mkfifo_sn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_User_constructor_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_setsid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_getgid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_setuid_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Pipe_constructor_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Rusage_constructor_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_ProcessStream_eos_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_ProcessStream___read___n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_ProcessStream___write___s );
FE_NATIVE_FUNCTION( ferite_posix_Posix_ProcessStream___close___ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_ProcessStream_constructor_o );
FE_NATIVE_FUNCTION( ferite_posix_Posix_exec_saa );
FE_NATIVE_FUNCTION( ferite_posix_Posix_getppid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_getegid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_stat_s );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isLink_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getAccessTime_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSuid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isFifo_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isCharDevice_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getOwnerID_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isDirectory_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getGroupID_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getChangedTime_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getModifiedTime_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isRegularFile_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSticky_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getInode_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getSize_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getBlockCount_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getBlockSize_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSgid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isBlockDevice_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_destructor_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_constructor_o );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_isSocket_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_Stat_getLinkCount_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_getpid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_waitpid_nn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_resetSigAction_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_getPriority_nn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_ignoreSignal_n );
FE_NATIVE_FUNCTION( ferite_posix_Posix_getuid_ );
FE_NATIVE_FUNCTION( ferite_posix_Posix_select_aaan );
FE_NATIVE_FUNCTION( ferite_posix_Posix_registerSigHandler_nso );
FE_NATIVE_FUNCTION( ferite_posix_Posix_chmod_sn );
FE_NATIVE_FUNCTION( ferite_posix_Posix_kill_nn );

#endif /* __posix_HEADER__ */
