/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __xml_HEADER__
#define __xml_HEADER__

#include <ferite.h>

FERITE_API void ferite_xml_register();
FERITE_API void ferite_xml_unregister();
FERITE_API void ferite_xml_init( FeriteScript *script );
FERITE_API void ferite_xml_deinit( FeriteScript *script );

    /* Start user defined header code */
  
	#include "sax_handlers.h"
	#include "tree_handlers.h"
	#include "xpath_handlers.h"

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_xml_XML_SAXParser_parseFile_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_SAXParser_destructor_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_SAXParser_parseChunk_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_SAXParser_constructor_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getElementsByTagName_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getFirstChild_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_setElementData_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getAttributeByName_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeChildWithName_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getAttributes_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getElementData_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_hasAttributes_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeElementsByTagName_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getPreviousSibling_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsSibling_o );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addCDATASection_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getNextSibling_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_setAttribute_ss );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addPI_ss );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getParent_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsPreviousSibling_o );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addSibling_ss );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_hasAttribute_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeChildren_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsNextSibling_o );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_setElementName_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getNamespace_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addPreviousSibling_ss );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_toString_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addNextSibling_ss );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeSelf_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getLastChild_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getElementName_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsChild_o );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getChildren_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeAttribute_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_hasChildren_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_destructor_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_constructor_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addChild_ss );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_xpathArray_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addComment_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_keepBlanks_b );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_parseFile_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_getDocumentElement_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_toString_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_saveToFile_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_validation_b );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_destructor_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_parseChunk_s );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_constructor_ );
FE_NATIVE_FUNCTION( ferite_xml_XML_TreeParser_xpathArray_s );

#endif /* __xml_HEADER__ */
