/* This file has been automatically generated by builder part of the ferite distribution */
/* file: xml_XML.c */
/* namespace: XML */

#include <ferite.h>       /* we need this without a doubt */
#include "xml_header.h"  /* this is the module header */

