/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  xml_XML_Element.c */
/* class: Element */

#include <ferite.h>       /* we need this without a doubt */
#include "xml_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getElementsByTagName_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 109 "xml.fec"

 
 FeriteVariable *array = NULL;
 FeriteVariable *obj = NULL;
	xmlXPathObjectPtr res = NULL;
 xmlNodeSetPtr cur = NULL;
 register int i = 0;
	XMLDoc *tree = self->odata; 

	res = get_nodes_with_name_xpath( tree, name ); 
	switch ( res->type ) {
 case XPATH_NODESET:
 cur = res->nodesetval;
 array = ferite_create_uarray_variable( script, "Nodes", FE_ARRAY_DEFAULT_SIZE, FE_STATIC );
 
 for (i = 0 ; i < cur->nodeNr ; i++) {
 obj = create_element_node( script, tree->doc, cur->nodeTab[i] );	
 ferite_uarray_add( script, VAUA( array ), obj, NULL, FE_ARRAY_ADD_AT_END );
 }
 break;
	default:
	printf("Unknown node type: %d\n", res->type );
 }	
 xmlXPathFreeObject( res );	
	FE_RETURN_VAR( array );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getFirstChild_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 260 "xml.fec"

 
 XMLDoc *tree = self->odata; 
 if( tree->node->children )
 {
 FeriteVariable *obj = NULL;
 obj = create_element_node( script, tree->doc, tree->node->children );
 FE_RETURN_VAR( obj ); 
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_setElementData_s )
{
   FeriteString *value = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &value );

   { /* Main function body. */
#line 579 "xml.fec"

	    
	        XMLDoc *tree = self->odata;
	        xmlNodeSetContent( tree->node, (xmlChar*)value->data );		
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getAttributeByName_s )
{
   FeriteString *attr = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &attr );

   { /* Main function body. */
#line 173 "xml.fec"

 FeriteString *str = NULL;
 xmlChar *value = NULL;
 XMLDoc *tree = self->odata; 
 
 value = xmlGetProp( tree->node, (xmlChar*)attr->data );
 if( value != NULL ) {
 str = ferite_str_new( script, (char *)value, 0, FE_CHARSET_DEFAULT );
 xmlFree( value );
 }
 FE_RETURN_STR( str, FE_TRUE );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeChildWithName_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 658 "xml.fec"

		  XMLDoc *tree = self->odata;
		  xmlNodePtr elem = NULL;
		  int count = 0;	

		  elem = tree->node->children;
		  while ( elem ) {
			  if(! strncmp( (char*)elem->name, name->data, name->length ) ) {
				  xmlUnlinkNode( elem );
				  count++;
			  }
			  elem = elem->next;
		  }
		  FE_RETURN_LONG( count );
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getAttributes_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 192 "xml.fec"

 
 xmlAttrPtr attr = NULL;
 xmlChar *key = NULL; 
 FeriteVariable *str = NULL;
 FeriteVariable *array = NULL;
 XMLDoc *tree = self->odata;
 
 attr = tree->node->properties;
 array = ferite_create_uarray_variable( script, "Attributes", FE_ARRAY_DEFAULT_SIZE, FE_STATIC );
 
 while ( attr != NULL ) {
 key = xmlGetProp(tree->node, attr->name);
 
 str = ferite_create_string_variable_from_ptr( script, (char *)attr->name, (char *) key, 
 0, FE_CHARSET_DEFAULT, FE_STATIC );
 ferite_uarray_add( script, VAUA( array ), str, (char*)attr->name, FE_ARRAY_ADD_AT_END );
 xmlFree( key );
 
 attr = attr->next;
 }
 FE_RETURN_VAR( array );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getElementData_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 89 "xml.fec"

 FeriteString *str = NULL;
 xmlChar *key = NULL;	
 XMLDoc *tree = self->odata; 
 
 key = xmlNodeGetContent(tree->node); /*xmlNodeListGetString(tree->doc, tree->node, 1);*/
 if( key != NULL ) {
 str = ferite_str_new( script, (char *)key, 0, FE_CHARSET_DEFAULT );
 xmlFree( key );
 }
 FE_RETURN_STR( str, FE_TRUE );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_hasAttributes_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 143 "xml.fec"

 XMLDoc *tree = self->odata; 
	if( tree->node->properties ) {
	FE_RETURN_TRUE;
	}
	FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeElementsByTagName_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 698 "xml.fec"

	        XMLDoc *tree = self->odata;	        
	        xmlXPathObjectPtr res = NULL; 
		xmlNodeSetPtr cur = NULL;
		register int i = 0;
		
		res = get_nodes_with_name_xpath( tree, name );
	        switch( res->type )
	        { 
	            case XPATH_NODESET:
	                cur = res->nodesetval;
                
	                for (i = 0 ; i < cur->nodeNr ; i++) {
	                    xmlUnlinkNode( cur->nodeTab[i] );
	                }
	                break;		
		}
	        xmlXPathFreeObject( res );
		FE_RETURN_LONG( i );	
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getPreviousSibling_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 314 "xml.fec"

 
 XMLDoc *tree = self->odata; 
 if( tree->node->prev )
 {
 FeriteVariable *obj = NULL;
 obj = create_element_node( script, tree->doc, tree->node->prev );
 FE_RETURN_VAR( obj ); 
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsSibling_o )
{
   FeriteObject *chk = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &chk );

   { /* Main function body. */
#line 756 "xml.fec"

	    
	        if( chk != NULL )
	        {
	            FeriteVariable *obj = NULL;
	            XMLDoc *tree = self->odata;
	            XMLDoc *chunk = chk->odata;
	            xmlNodePtr ret = NULL;
            
	            if( (void*)(tree->node->parent) != (void*)(tree->doc) )
	            {
	                ret = xmlCopyNode( chunk->node, 1 ); 
	                if( ret != NULL ) {
	                    xmlAddSibling(tree->node, ret);
	                    recursive_namespace_copy( ret, tree->node->parent );
	                    obj = create_element_node( script, tree->doc, ret );
	                    FE_RETURN_VAR( obj );
	                }
	            }
	        }
	        FE_RETURN_NULL_OBJECT;          
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addCDATASection_s )
{
   FeriteString *cdata = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &cdata );

   { /* Main function body. */
#line 525 "xml.fec"

			XMLDoc *tree = self->odata;
			xmlNodePtr node = NULL, ret = NULL;
		
			node = xmlNewCDataBlock( NULL , (xmlChar*)cdata->data, cdata->length );
			if( node != NULL ) {
	            ret = xmlAddChild(tree->node, node);
	            recursive_namespace_copy( ret, tree->node );
	            FE_RETURN_TRUE;
			}
			FE_RETURN_FALSE;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getNextSibling_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 332 "xml.fec"

 
 XMLDoc *tree = self->odata; 
 if( tree->node->next )
 {
 FeriteVariable *obj = NULL;
 obj = create_element_node( script, tree->doc, tree->node->next );
 FE_RETURN_VAR( obj ); 
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_setAttribute_ss )
{
   FeriteString *name = NULL;
   FeriteString *value = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, &value );

   { /* Main function body. */
#line 593 "xml.fec"

	    
	        XMLDoc *tree = self->odata;
	        xmlAttrPtr attr = NULL;
        
			if( xmlHasProp( tree->node, (xmlChar*)name->data ) ) {
	            xmlSetProp( tree->node, (xmlChar*)name->data, (xmlChar*)value->data );
	        } else {
	            attr = xmlNewProp( tree->node, (xmlChar*)name->data, (xmlChar*)value->data );
	            xmlAddChild( tree->node, (xmlNodePtr)attr );
	        }
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addPI_ss )
{
   FeriteString *name = NULL;
   FeriteString *value = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, &value );

   { /* Main function body. */
#line 547 "xml.fec"

			XMLDoc *tree = self->odata;
			xmlNodePtr node = NULL;
	        xmlNodePtr ret = NULL;
	
			node = xmlNewPI( (xmlChar*)name->data, (xmlChar*)value->data );
			if( node != NULL ) {
	            ret = xmlAddChild(tree->node, node);
	            recursive_namespace_copy( ret, tree->node );
	            FE_RETURN_TRUE;
			}
			FE_RETURN_FALSE;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getParent_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 296 "xml.fec"

 
 XMLDoc *tree = self->odata; 
 if( tree->node->parent )
 {
 FeriteVariable *obj = NULL;
 obj = create_element_node( script, tree->doc, tree->node->parent );
 FE_RETURN_VAR( obj ); 
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsPreviousSibling_o )
{
   FeriteObject *chk = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &chk );

   { /* Main function body. */
#line 818 "xml.fec"

	    
	        if( chk != NULL )
	        {
	            FeriteVariable *obj = NULL;
	            XMLDoc *tree = self->odata;
	            XMLDoc *chunk = chk->odata;
	            xmlNodePtr ret = NULL;
            
	            if( (void*)(tree->node->parent) != (void*)(tree->doc) )
	            {
	                ret = xmlCopyNode( chunk->node, 1 ); 
	                if( ret != NULL ) {
	                    xmlAddPrevSibling(tree->node, ret);
	                    recursive_namespace_copy( ret, tree->node->parent );
	                    obj = create_element_node( script, tree->doc, ret );
	                    FE_RETURN_VAR( obj );
	                }
	            }
	        }
	        FE_RETURN_NULL_OBJECT;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addSibling_ss )
{
   FeriteString *name = NULL;
   FeriteString *data = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, &data );

   { /* Main function body. */
#line 406 "xml.fec"
 
			FeriteVariable *obj = NULL;
			XMLDoc *tree = self->odata;
			xmlNodePtr node = NULL;
			xmlNodePtr ret = NULL;
			xmlChar *value = NULL;	
        
	        if( (void*)(tree->node->parent) != (void*)(tree->doc) )
	        {
	            if( data->length ) 
	                value = (xmlChar*)data->data;	
            
	            node = xmlNewDocNode( tree->doc, NULL, (xmlChar*)name->data, value );
	            if( node != NULL ) {
	                node->doc = tree->doc;
	                ret = xmlAddSibling( tree->node, node );
	                recursive_namespace_copy( ret, tree->node->parent );
	                obj = create_element_node( script, tree->doc, ret );
	                FE_RETURN_VAR( obj );
	            }
	        }
			FE_RETURN_NULL_OBJECT;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_hasAttribute_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 159 "xml.fec"

	XMLDoc *tree = self->odata;	
	if( xmlHasProp( tree->node, (xmlChar*)name->data ) ) 
 FE_RETURN_TRUE;
	FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeChildren_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 634 "xml.fec"

	          XMLDoc *tree = self->odata;
		  xmlNodePtr elem = NULL;
		  int count = 0;

		  elem = tree->node->children;
		  while ( elem ) {
	                xmlUnlinkNode( elem );
		        count++;
	                elem = elem->next;
		  }

		  tree->node->children = tree->node->last = NULL;
		  FE_RETURN_LONG( count ); 
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsNextSibling_o )
{
   FeriteObject *chk = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &chk );

   { /* Main function body. */
#line 787 "xml.fec"

 
 if( chk != NULL )
 {
 FeriteVariable *obj = NULL;
 XMLDoc *tree = self->odata;
 XMLDoc *chunk = chk->odata;
 xmlNodePtr ret = NULL;
 
 if( (void*)(tree->node->parent) != (void*)(tree->doc) )
 {
 ret = xmlCopyNode( chunk->node, 1 ); 
 if( ret != NULL ) {
 xmlAddNextSibling(tree->node, ret);
 recursive_namespace_copy( ret, tree->node->parent );
 obj = create_element_node( script, tree->doc, ret );
 FE_RETURN_VAR( obj );
 }
 }
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_setElementName_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 567 "xml.fec"

	    
			XMLDoc *tree = self->odata;
			xmlNodeSetName(tree->node, (xmlChar*)name->data);
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getNamespace_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 351 "xml.fec"

 FeriteVariable *arr = NULL;
 XMLDoc *tree = self->odata; 
 int i = 0;
 
 arr = ferite_create_uarray_variable( script, "NamespaceList", FE_ARRAY_DEFAULT_SIZE, FE_STATIC );
 if( tree->node->ns != NULL )
 {
 FeriteVariable *str = ferite_create_string_variable_from_ptr( script, "URL", (char *)(tree->node->ns->href), 
 0, FE_CHARSET_DEFAULT, FE_STATIC );
 ferite_uarray_add( script, VAUA( arr ), str, (char *)(tree->node->ns->prefix), FE_ARRAY_ADD_AT_END );
 }
 FE_RETURN_VAR( arr );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addPreviousSibling_ss )
{
   FeriteString *name = NULL;
   FeriteString *data = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, &data );

   { /* Main function body. */
#line 472 "xml.fec"
 
			FeriteVariable *obj = NULL;
			XMLDoc *tree = self->odata;
			xmlNodePtr node = NULL;
			xmlNodePtr ret = NULL;
			xmlChar *value = NULL;	
        
	        if( (void*)(tree->node->parent) != (void*)(tree->doc) )
	        {
	            if( data->length ) 
	                value = (xmlChar*)data->data;	
            
	            node = xmlNewDocNode( tree->doc, NULL, (xmlChar*)name->data, value );
	            if( node != NULL ) {
	                node->doc = tree->doc;
	                ret = xmlAddPrevSibling( tree->node, node );
	                recursive_namespace_copy( ret, tree->node->parent );
	                obj = create_element_node( script, tree->doc, ret );
	                FE_RETURN_VAR( obj );
	            }
	        }
			FE_RETURN_NULL_OBJECT;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_toString_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 848 "xml.fec"

	        XMLDoc *tree = self->odata;
	        FeriteVariable *v = NULL;
        
	        if( tree->doc )
	        {
	            xmlChar *xmlstring = NULL;
		    xmlBufferPtr buffer = xmlBufferCreate();
	            int len;
            
	            xmlIndentTreeOutput = 1;
	            xmlNodeDump( buffer, tree->doc, tree->node, 100, 1);
	
	            xmlstring = xmlBufferContent( buffer );
		    len = xmlBufferLength( buffer );
	            v = fe_new_str_static( "xml", (char *)xmlstring, len, FE_CHARSET_DEFAULT );
            
		    xmlBufferFree( buffer );

	        }
	        else
	            v = fe_new_str_static( "xml", "", 0, FE_CHARSET_DEFAULT );
        

	        FE_RETURN_VAR( v );
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addNextSibling_ss )
{
   FeriteString *name = NULL;
   FeriteString *data = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, &data );

   { /* Main function body. */
#line 439 "xml.fec"
 
	FeriteVariable *obj = NULL;
	XMLDoc *tree = self->odata;
	xmlNodePtr node = NULL;
	xmlNodePtr ret = NULL;
	xmlChar *value = NULL;	
 
 if( (void*)(tree->node->parent) != (void*)(tree->doc) )
 {
 if( data->length ) 
 value = (xmlChar*)data->data;	
 
 node = xmlNewDocNode( tree->doc, NULL, (xmlChar*)name->data, value );
 if( node != NULL ) {
 node->doc = tree->doc;
 ret = xmlAddNextSibling( tree->node, node );
 recursive_namespace_copy( ret, tree->node->parent );
 obj = create_element_node( script, tree->doc, ret );
 FE_RETURN_VAR( obj );
 }
 }
	FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeSelf_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 679 "xml.fec"

	    
		  XMLDoc *tree = self->odata;
		  xmlNodePtr elem = NULL;
	
		  elem = tree->node;
		  tree->node = tree->node->next;
		
		  xmlUnlinkNode( elem );	  
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getLastChild_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 278 "xml.fec"

 
 XMLDoc *tree = self->odata; 
 if( tree->node->last )
 {
 FeriteVariable *obj = NULL;
 obj = create_element_node( script, tree->doc, tree->node->last );
 FE_RETURN_VAR( obj ); 
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getElementName_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 74 "xml.fec"

 XMLDoc *tree = self->odata;
 FeriteString *str = NULL;	
	
 str = ferite_str_new( script, (char *)tree->node->name, 0, FE_CHARSET_DEFAULT );
 FE_RETURN_STR( str, FE_TRUE );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_mergeAsChild_o )
{
   FeriteObject *chk = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &chk );

   { /* Main function body. */
#line 728 "xml.fec"

 
 if( chk != NULL )
 {
 FeriteVariable *obj = NULL;
 XMLDoc *tree = self->odata;
 XMLDoc *chunk = chk->odata;
 xmlNodePtr ret = NULL;
 
 ret = xmlCopyNode( chunk->node, 1 ); 
 if( ret != NULL ) {
 xmlAddChild(tree->node, ret);
 recursive_namespace_copy( ret, tree->node );
 obj = create_element_node( script, tree->doc, ret );
 FE_RETURN_VAR( obj );
 }
 }
 FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_getChildren_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 237 "xml.fec"
 
 FeriteVariable *obj;
 FeriteVariable *array = NULL;
 xmlNodePtr cur = NULL;
 XMLDoc *tree = self->odata; 
 
 cur = tree->node->children;
 array = ferite_create_uarray_variable( script, "Children", FE_ARRAY_DEFAULT_SIZE, FE_STATIC );
 
 while ( cur ) {
 obj = create_element_node( script, tree->doc, cur );
 ferite_uarray_add( script, VAUA( array ), obj, NULL, FE_ARRAY_ADD_AT_END );
 cur = cur->next;
 }
 FE_RETURN_VAR( array );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_removeAttribute_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 613 "xml.fec"

	        xmlAttrPtr attr = NULL;
	        XMLDoc *tree = self->odata;
    	
	        attr = xmlHasProp( tree->node,(xmlChar*)name->data );
        
	        if( attr != NULL ) {
	            xmlUnlinkNode((xmlNodePtr)attr);
	            xmlFreeProp(attr);
	            FE_RETURN_TRUE;
	        }
			FE_RETURN_FALSE;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_hasChildren_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 223 "xml.fec"

 XMLDoc *tree = self->odata;
	if( tree->node->children ) {
	FE_RETURN_TRUE;
	}
	FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_destructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 62 "xml.fec"

 XMLDoc *tree = self->odata;
 if(tree != NULL) ffree(tree);
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 56 "xml.fec"

 XMLDoc *tree = fmalloc( sizeof(XMLDoc) );	
 self->odata = tree;	
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addChild_ss )
{
   FeriteString *name = NULL;
   FeriteString *data = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, &data );

   { /* Main function body. */
#line 376 "xml.fec"

 
	FeriteVariable *obj = NULL;
	XMLDoc *tree = self->odata;
	xmlNodePtr node = NULL;
	xmlNodePtr ret = NULL;
	xmlChar *value = NULL;	
 
	if( data->length ) 
 value = (xmlChar*)data->data;	
 
	node = xmlNewDocNode( tree->doc, NULL, (xmlChar*)name->data, value );
	if( node != NULL ) {
 ret = xmlAddChild( tree->node, node );
 recursive_namespace_copy( ret, tree->node );
 obj = create_element_node( script, tree->doc, ret );
 FE_RETURN_VAR( obj );
	}
	FE_RETURN_NULL_OBJECT;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_xpathArray_s )
{
   FeriteString *expr = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &expr );

   { /* Main function body. */
#line 883 "xml.fec"
 
	        FeriteVariable *v = NULL;
	        XMLDoc *tree = self->odata;
        
	        if( tree->doc ) 
	            v = ParseXPath( script, tree , (const char *) expr->data);
	        else 
	            v = fe_new_array_static( "xpathArray", 0 );
        
	        FE_RETURN_VAR( v );
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_xml_XML_Element_addComment_s )
{
   FeriteString *comment = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &comment );

   { /* Main function body. */
#line 504 "xml.fec"

			XMLDoc *tree = self->odata;
			xmlNodePtr node = NULL, ret = NULL;
		
			node = xmlNewComment( (xmlChar*)comment->data );	
			if( node != NULL ) {
	            ret = xmlAddChild(tree->node, node);
	            recursive_namespace_copy( ret, tree->node );
	            FE_RETURN_TRUE;
			}
			FE_RETURN_FALSE;
	    
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

