/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "xml_header.h"  /* this is the module header */

void ferite_xml_register()
{
      ferite_module_register_native_function( "XML.SAXParser.parseFile_s", ferite_xml_XML_SAXParser_parseFile_s );
      ferite_module_register_native_function( "XML.SAXParser.destructor_", ferite_xml_XML_SAXParser_destructor_ );
      ferite_module_register_native_function( "XML.SAXParser.parseChunk_s", ferite_xml_XML_SAXParser_parseChunk_s );
      ferite_module_register_native_function( "XML.SAXParser.constructor_", ferite_xml_XML_SAXParser_constructor_ );
      ferite_module_register_native_function( "XML.Element.getElementsByTagName_s", ferite_xml_XML_Element_getElementsByTagName_s );
      ferite_module_register_native_function( "XML.Element.getFirstChild_", ferite_xml_XML_Element_getFirstChild_ );
      ferite_module_register_native_function( "XML.Element.setElementData_s", ferite_xml_XML_Element_setElementData_s );
      ferite_module_register_native_function( "XML.Element.getAttributeByName_s", ferite_xml_XML_Element_getAttributeByName_s );
      ferite_module_register_native_function( "XML.Element.removeChildWithName_s", ferite_xml_XML_Element_removeChildWithName_s );
      ferite_module_register_native_function( "XML.Element.getAttributes_", ferite_xml_XML_Element_getAttributes_ );
      ferite_module_register_native_function( "XML.Element.getElementData_", ferite_xml_XML_Element_getElementData_ );
      ferite_module_register_native_function( "XML.Element.hasAttributes_", ferite_xml_XML_Element_hasAttributes_ );
      ferite_module_register_native_function( "XML.Element.removeElementsByTagName_s", ferite_xml_XML_Element_removeElementsByTagName_s );
      ferite_module_register_native_function( "XML.Element.getPreviousSibling_", ferite_xml_XML_Element_getPreviousSibling_ );
      ferite_module_register_native_function( "XML.Element.mergeAsSibling_o", ferite_xml_XML_Element_mergeAsSibling_o );
      ferite_module_register_native_function( "XML.Element.addCDATASection_s", ferite_xml_XML_Element_addCDATASection_s );
      ferite_module_register_native_function( "XML.Element.getNextSibling_", ferite_xml_XML_Element_getNextSibling_ );
      ferite_module_register_native_function( "XML.Element.setAttribute_ss", ferite_xml_XML_Element_setAttribute_ss );
      ferite_module_register_native_function( "XML.Element.addPI_ss", ferite_xml_XML_Element_addPI_ss );
      ferite_module_register_native_function( "XML.Element.getParent_", ferite_xml_XML_Element_getParent_ );
      ferite_module_register_native_function( "XML.Element.mergeAsPreviousSibling_o", ferite_xml_XML_Element_mergeAsPreviousSibling_o );
      ferite_module_register_native_function( "XML.Element.addSibling_ss", ferite_xml_XML_Element_addSibling_ss );
      ferite_module_register_native_function( "XML.Element.hasAttribute_s", ferite_xml_XML_Element_hasAttribute_s );
      ferite_module_register_native_function( "XML.Element.removeChildren_", ferite_xml_XML_Element_removeChildren_ );
      ferite_module_register_native_function( "XML.Element.mergeAsNextSibling_o", ferite_xml_XML_Element_mergeAsNextSibling_o );
      ferite_module_register_native_function( "XML.Element.setElementName_s", ferite_xml_XML_Element_setElementName_s );
      ferite_module_register_native_function( "XML.Element.getNamespace_", ferite_xml_XML_Element_getNamespace_ );
      ferite_module_register_native_function( "XML.Element.addPreviousSibling_ss", ferite_xml_XML_Element_addPreviousSibling_ss );
      ferite_module_register_native_function( "XML.Element.toString_", ferite_xml_XML_Element_toString_ );
      ferite_module_register_native_function( "XML.Element.addNextSibling_ss", ferite_xml_XML_Element_addNextSibling_ss );
      ferite_module_register_native_function( "XML.Element.removeSelf_", ferite_xml_XML_Element_removeSelf_ );
      ferite_module_register_native_function( "XML.Element.getLastChild_", ferite_xml_XML_Element_getLastChild_ );
      ferite_module_register_native_function( "XML.Element.getElementName_", ferite_xml_XML_Element_getElementName_ );
      ferite_module_register_native_function( "XML.Element.mergeAsChild_o", ferite_xml_XML_Element_mergeAsChild_o );
      ferite_module_register_native_function( "XML.Element.getChildren_", ferite_xml_XML_Element_getChildren_ );
      ferite_module_register_native_function( "XML.Element.removeAttribute_s", ferite_xml_XML_Element_removeAttribute_s );
      ferite_module_register_native_function( "XML.Element.hasChildren_", ferite_xml_XML_Element_hasChildren_ );
      ferite_module_register_native_function( "XML.Element.destructor_", ferite_xml_XML_Element_destructor_ );
      ferite_module_register_native_function( "XML.Element.constructor_", ferite_xml_XML_Element_constructor_ );
      ferite_module_register_native_function( "XML.Element.addChild_ss", ferite_xml_XML_Element_addChild_ss );
      ferite_module_register_native_function( "XML.Element.xpathArray_s", ferite_xml_XML_Element_xpathArray_s );
      ferite_module_register_native_function( "XML.Element.addComment_s", ferite_xml_XML_Element_addComment_s );
      ferite_module_register_native_function( "XML.TreeParser.keepBlanks_b", ferite_xml_XML_TreeParser_keepBlanks_b );
      ferite_module_register_native_function( "XML.TreeParser.parseFile_s", ferite_xml_XML_TreeParser_parseFile_s );
      ferite_module_register_native_function( "XML.TreeParser.getDocumentElement_", ferite_xml_XML_TreeParser_getDocumentElement_ );
      ferite_module_register_native_function( "XML.TreeParser.toString_", ferite_xml_XML_TreeParser_toString_ );
      ferite_module_register_native_function( "XML.TreeParser.saveToFile_s", ferite_xml_XML_TreeParser_saveToFile_s );
      ferite_module_register_native_function( "XML.TreeParser.validation_b", ferite_xml_XML_TreeParser_validation_b );
      ferite_module_register_native_function( "XML.TreeParser.destructor_", ferite_xml_XML_TreeParser_destructor_ );
      ferite_module_register_native_function( "XML.TreeParser.parseChunk_s", ferite_xml_XML_TreeParser_parseChunk_s );
      ferite_module_register_native_function( "XML.TreeParser.constructor_", ferite_xml_XML_TreeParser_constructor_ );
      ferite_module_register_native_function( "XML.TreeParser.xpathArray_s", ferite_xml_XML_TreeParser_xpathArray_s );
}

void ferite_xml_init( FeriteScript *script )
{
}

void ferite_xml_deinit( FeriteScript *script )
{
    /* Start user defined deinitialisation code */
 
 xmlCleanupParser(); /* cleanup global vars in libxml2 */

    /* End user defined deinitialisation code */
}

void ferite_xml_unregister()
{
}

