/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __array_HEADER__
#define __array_HEADER__

#include <ferite.h>

FERITE_API void ferite_array_register();
FERITE_API void ferite_array_unregister();
FERITE_API void ferite_array_init( FeriteScript *script );
FERITE_API void ferite_array_deinit( FeriteScript *script );

    /* Start user defined header code */



#include <stdlib.h>
#include "util.h"

#ifdef VCWIN32
# include <snprintf.h>
#endif


    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_array_Array_getName_an );
FE_NATIVE_FUNCTION( ferite_array_Array_size_a );
FE_NATIVE_FUNCTION( ferite_array_Array_shift_a );
FE_NATIVE_FUNCTION( ferite_array_Array_unshift_av );
FE_NATIVE_FUNCTION( ferite_array_Array___join_as );
FE_NATIVE_FUNCTION( ferite_array_Array_del_av );
FE_NATIVE_FUNCTION( ferite_array_Array_valueExists_av );
FE_NATIVE_FUNCTION( ferite_array_Array__print_a );
FE_NATIVE_FUNCTION( ferite_array_Array_pop_a );
FE_NATIVE_FUNCTION( ferite_array_Array_resize_an );
FE_NATIVE_FUNCTION( ferite_array_Array_keys_a );
FE_NATIVE_FUNCTION( ferite_array_Array_push_av );
FE_NATIVE_FUNCTION( ferite_array_Array_keyExists_as );
FE_NATIVE_FUNCTION( ferite_array_Array_getIndex_as );
FE_NATIVE_FUNCTION( ferite_array_Array_sort_an );

#endif /* __array_HEADER__ */
