/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "array_header.h"  /* this is the module header */

void ferite_array_register()
{
      ferite_module_register_native_function( "Array.getName_an", ferite_array_Array_getName_an );
      ferite_module_register_native_function( "Array.size_a", ferite_array_Array_size_a );
      ferite_module_register_native_function( "Array.shift_a", ferite_array_Array_shift_a );
      ferite_module_register_native_function( "Array.unshift_av", ferite_array_Array_unshift_av );
      ferite_module_register_native_function( "Array.__join_as", ferite_array_Array___join_as );
      ferite_module_register_native_function( "Array.del_av", ferite_array_Array_del_av );
      ferite_module_register_native_function( "Array.valueExists_av", ferite_array_Array_valueExists_av );
      ferite_module_register_native_function( "Array._print_a", ferite_array_Array__print_a );
      ferite_module_register_native_function( "Array.pop_a", ferite_array_Array_pop_a );
      ferite_module_register_native_function( "Array.resize_an", ferite_array_Array_resize_an );
      ferite_module_register_native_function( "Array.keys_a", ferite_array_Array_keys_a );
      ferite_module_register_native_function( "Array.push_av", ferite_array_Array_push_av );
      ferite_module_register_native_function( "Array.keyExists_as", ferite_array_Array_keyExists_as );
      ferite_module_register_native_function( "Array.getIndex_as", ferite_array_Array_getIndex_as );
      ferite_module_register_native_function( "Array.sort_an", ferite_array_Array_sort_an );
}

void ferite_array_init( FeriteScript *script )
{
}

void ferite_array_deinit( FeriteScript *script )
{
}

void ferite_array_unregister()
{
}

