/* This file has been automatically generated by builder part of the ferite distribution */
/* file: network_Network.c */
/* namespace: Network */

#include <ferite.h>       /* we need this without a doubt */
#include "network_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_network_Network_getServiceByName_ss )
{
   FeriteString *name = NULL;
   FeriteString *proto = NULL;
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 2, &name, &proto );

   { /* Main function body. */
#line 576 "network.fec"

 
 char *prot;
 FeriteVariable *fv;
 struct servent *se;

 if(proto->data[0]) prot = proto->data;
 else prot = NULL;

 if(!(se = getservbyname(name->data, prot)))
 FE_RETURN_NULL_OBJECT;

 fv = servent_to_Service(script, se);
 FE_RETURN_VAR(fv);
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_network_Network_getHostname_ )
{
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   { /* Main function body. */
#line 486 "network.fec"

 char buf[256];

 gethostname(buf, 256);

 FE_RETURN_VAR(ferite_create_string_variable_from_ptr(script, "Hostname", buf, 0, FE_CHARSET_DEFAULT, FE_STATIC));
 
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_network_Network_getServiceByPort_ns )
{
   double port = 0.0;
   FeriteString *proto = NULL;
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 2, &port, &proto );

   { /* Main function body. */
#line 541 "network.fec"

    
        char *prot;
        FeriteVariable *fv;
        struct servent *se;

        if(proto->data[0]) prot = proto->data;
        else prot = NULL;

        if(!(se = getservbyport(htons((int)port), prot)))
          FE_RETURN_NULL_OBJECT;

        fv = servent_to_Service(script, se);
        FE_RETURN_VAR(fv);
    
   }
   FE_RETURN_VOID;
   self = NULL;
}

