/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  network_Network_Service.c */
/* class: Service */

#include <ferite.h>       /* we need this without a doubt */
#include "network_header.h"  /* this is the module header */

