/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "network_header.h"  /* this is the module header */

void ferite_network_register()
{
      ferite_module_register_native_function( "Network.UDP.Stream.__read___n", ferite_network_Network_UDP_Stream___read___n );
      ferite_module_register_native_function( "Network.UDP.Stream.__write___s", ferite_network_Network_UDP_Stream___write___s );
      ferite_module_register_native_function( "Network.UDP.Stream.__close___", ferite_network_Network_UDP_Stream___close___ );
      ferite_module_register_native_function( "Network.UDP.connect_snn", ferite_network_Network_UDP_connect_snn );
      ferite_module_register_native_function( "Network.UDP.bind_snn", ferite_network_Network_UDP_bind_snn );
      ferite_module_register_native_function( "Network.getServiceByName_ss", ferite_network_Network_getServiceByName_ss );
      ferite_module_register_native_function( "Network.TCP.Stream.listen_n", ferite_network_Network_TCP_Stream_listen_n );
      ferite_module_register_native_function( "Network.TCP.Stream.accept_", ferite_network_Network_TCP_Stream_accept_ );
      ferite_module_register_native_function( "Network.TCP.Stream.__read___n", ferite_network_Network_TCP_Stream___read___n );
      ferite_module_register_native_function( "Network.TCP.Stream.__write___s", ferite_network_Network_TCP_Stream___write___s );
      ferite_module_register_native_function( "Network.TCP.connect_snn", ferite_network_Network_TCP_connect_snn );
      ferite_module_register_native_function( "Network.TCP.bind_snn", ferite_network_Network_TCP_bind_snn );
      ferite_module_register_native_function( "Network.Host.constructor_snn", ferite_network_Network_Host_constructor_snn );
      ferite_module_register_native_function( "Network.getHostname_", ferite_network_Network_getHostname_ );
      ferite_module_register_native_function( "Network.getServiceByPort_ns", ferite_network_Network_getServiceByPort_ns );
    /* Start user defined register code */
 

#ifdef WIN32
{
	WSADATA wsaData;
	WSAStartup( MAKEWORLD(2,0), &wsaData );
}
#endif


    /* End user defined register code */
}

void ferite_network_init( FeriteScript *script )
{
}

void ferite_network_deinit( FeriteScript *script )
{
}

void ferite_network_unregister()
{
}

