/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __network_HEADER__
#define __network_HEADER__

#include <ferite.h>

FERITE_API void ferite_network_register();
FERITE_API void ferite_network_unregister();
FERITE_API void ferite_network_init( FeriteScript *script );
FERITE_API void ferite_network_deinit( FeriteScript *script );

    /* Start user defined header code */
 

#include "../../config.h"
#include "util_network.h"


    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_network_Network_UDP_Stream___read___n );
FE_NATIVE_FUNCTION( ferite_network_Network_UDP_Stream___write___s );
FE_NATIVE_FUNCTION( ferite_network_Network_UDP_Stream___close___ );
FE_NATIVE_FUNCTION( ferite_network_Network_UDP_connect_snn );
FE_NATIVE_FUNCTION( ferite_network_Network_UDP_bind_snn );
FE_NATIVE_FUNCTION( ferite_network_Network_getServiceByName_ss );
FE_NATIVE_FUNCTION( ferite_network_Network_TCP_Stream_listen_n );
FE_NATIVE_FUNCTION( ferite_network_Network_TCP_Stream_accept_ );
FE_NATIVE_FUNCTION( ferite_network_Network_TCP_Stream___read___n );
FE_NATIVE_FUNCTION( ferite_network_Network_TCP_Stream___write___s );
FE_NATIVE_FUNCTION( ferite_network_Network_TCP_connect_snn );
FE_NATIVE_FUNCTION( ferite_network_Network_TCP_bind_snn );
FE_NATIVE_FUNCTION( ferite_network_Network_Host_constructor_snn );
FE_NATIVE_FUNCTION( ferite_network_Network_getHostname_ );
FE_NATIVE_FUNCTION( ferite_network_Network_getServiceByPort_ns );

#endif /* __network_HEADER__ */
