/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  network_Network_Host.c */
/* class: Host */

#include <ferite.h>       /* we need this without a doubt */
#include "network_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_network_Network_Host_constructor_snn )
{
   FeriteString *host = NULL;
   double type = 0.0;
   double reverse = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 3, &host, &type, &reverse );

   { /* Main function body. */
#line 648 "network.fec"

           if(host_constructor(script, self, host->data, (int)type,
                               (int)reverse))
           {
               FE_RETURN_NULL_OBJECT;
           }
       
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

