/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  regexp_MatchObject.c */
/* class: MatchObject */

#include <ferite.h>       /* we need this without a doubt */
#include "regexp_header.h"  /* this is the module header */

