/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __regexp_HEADER__
#define __regexp_HEADER__

#include <ferite.h>

FERITE_API void ferite_regexp_register();
FERITE_API void ferite_regexp_unregister();
FERITE_API void ferite_regexp_init( FeriteScript *script );
FERITE_API void ferite_regexp_deinit( FeriteScript *script );

    /* Start user defined header code */
 


#include <pcre.h>
	
#define RegexpObject ((FeriteRegex*)self->odata)
#define fe_isnumeric( c ) (c >= '0' && c <= '9')
	

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_regexp_Regexp___compile_ );
FE_NATIVE_FUNCTION( ferite_regexp_Regexp___regexp_ssbb );
FE_NATIVE_FUNCTION( ferite_regexp_Regexp_destructor_ );

#endif /* __regexp_HEADER__ */
