/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "regexp_header.h"  /* this is the module header */

void ferite_regexp_register()
{
      ferite_module_register_native_function( "Regexp.__compile_", ferite_regexp_Regexp___compile_ );
      ferite_module_register_native_function( "Regexp.__regexp_ssbb", ferite_regexp_Regexp___regexp_ssbb );
      ferite_module_register_native_function( "Regexp.destructor_", ferite_regexp_Regexp_destructor_ );
}

void ferite_regexp_init( FeriteScript *script )
{
}

void ferite_regexp_deinit( FeriteScript *script )
{
}

void ferite_regexp_unregister()
{
}

