/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __reflection_HEADER__
#define __reflection_HEADER__

#include <ferite.h>

FERITE_API void ferite_reflection_register();
FERITE_API void ferite_reflection_unregister();
FERITE_API void ferite_reflection_init( FeriteScript *script );
FERITE_API void ferite_reflection_deinit( FeriteScript *script );

    /* Start user defined header code */



#include <string.h>

#define ClassObj ((FeriteClass*)(self->odata))
#define ObjectObj	((ObjectHolder*)(self->odata))
#define FunctionObj ((FunctionHolder*)(self->odata))
#define NSObj	((FeriteNamespace*)(self->odata))

#define ChkSelf \
	if(ClassObj == NULL) { \
 ferite_error(script, 0, "Undefined Class\n"); \
	}

	typedef struct __function_holder
	{
	FeriteFunction *func;
	void *container;
	}
	FunctionHolder;

	typedef struct __object_holder {
	FeriteObject *object;
	char weakReference;
	} ObjectHolder;

	void reflection_variable_get( FeriteScript *script, FeriteVariable *var );
	void reflection_variable_set( FeriteScript *script, FeriteVariable *var, FeriteVariable *newvalue );
	void reflection_variable_cleanup( FeriteScript *script, void *odata );
	char *reflection_generate_class_fqn( FeriteScript *script, FeriteClass *klass );
	FeriteVariable *reflection_ns_get_list( FeriteScript *script, FeriteNamespace *space, int type );

    /* End user defined header code */

FE_NATIVE_FUNCTION( ferite_reflection_Reflection_type_v );
FE_NATIVE_FUNCTION( ferite_reflection_Function_getReturnType_ );
FE_NATIVE_FUNCTION( ferite_reflection_Function_getParameterDetails_ );
FE_NATIVE_FUNCTION( ferite_reflection_Function_exec_E );
FE_NATIVE_FUNCTION( ferite_reflection_Function_serializeSleep_ );
FE_NATIVE_FUNCTION( ferite_reflection_Function_isNative_ );
FE_NATIVE_FUNCTION( ferite_reflection_Function_execWithArray_a );
FE_NATIVE_FUNCTION( ferite_reflection_Function_destructor_ );
FE_NATIVE_FUNCTION( ferite_reflection_Function_constructor_vs );
FE_NATIVE_FUNCTION( ferite_reflection_Function_constructor_s );
FE_NATIVE_FUNCTION( ferite_reflection_Class_getVariables_ );
FE_NATIVE_FUNCTION( ferite_reflection_Class_getClass_ );
FE_NATIVE_FUNCTION( ferite_reflection_Class_serializeSleep_ );
FE_NATIVE_FUNCTION( ferite_reflection_Class_fullyQualifiedName_ );
FE_NATIVE_FUNCTION( ferite_reflection_Class_getFunctions_ );
FE_NATIVE_FUNCTION( ferite_reflection_Class_constructor_v );
FE_NATIVE_FUNCTION( ferite_reflection_Class_newObject_E );
FE_NATIVE_FUNCTION( ferite_reflection_Class_classWithName_s );
FE_NATIVE_FUNCTION( ferite_reflection_Class_name_v );
FE_NATIVE_FUNCTION( ferite_reflection_Class_locate_s );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getVariables_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_serializeSleep_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_fullyQualifiedName_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getNamespace_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getFunctions_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getNamespaces_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getClasses_ );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getVariable_s );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_constructor_v );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_setVariable_sv );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_locate_s );
FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getScriptNamespace_ );
FE_NATIVE_FUNCTION( ferite_reflection_Variable_serializeSleep_ );
FE_NATIVE_FUNCTION( ferite_reflection_Variable_constructor_v );
FE_NATIVE_FUNCTION( ferite_reflection_Object_getVariables_ );
FE_NATIVE_FUNCTION( ferite_reflection_Object_hasFunction_s );
FE_NATIVE_FUNCTION( ferite_reflection_Object_serializeSleep_ );
FE_NATIVE_FUNCTION( ferite_reflection_Object_className_ );
FE_NATIVE_FUNCTION( ferite_reflection_Object_setWeakReference_b );
FE_NATIVE_FUNCTION( ferite_reflection_Object_getVariable_s );
FE_NATIVE_FUNCTION( ferite_reflection_Object_setVariables_a );
FE_NATIVE_FUNCTION( ferite_reflection_Object_getObject_ );
FE_NATIVE_FUNCTION( ferite_reflection_Object_hasVariable_s );
FE_NATIVE_FUNCTION( ferite_reflection_Object_destructor_ );
FE_NATIVE_FUNCTION( ferite_reflection_Object_constructor_o );
FE_NATIVE_FUNCTION( ferite_reflection_Object_constructor_ );
FE_NATIVE_FUNCTION( ferite_reflection_Object_setVariable_sv );
FE_NATIVE_FUNCTION( ferite_reflection_Object_hasMember_os );
FE_NATIVE_FUNCTION( ferite_reflection_Object_fromData_sa );

#endif /* __reflection_HEADER__ */
