/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  reflection_Variable.c */
/* class: Variable */

#include <ferite.h>       /* we need this without a doubt */
#include "reflection_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_reflection_Variable_serializeSleep_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 1304 "reflection.fec"
 
	ferite_error(script,0,"Can not serialize reflection Variables\n");
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Variable_constructor_v )
{
   FeriteVariable *var = params[0];
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, NULL );

   { /* Main function body. */
#line 1294 "reflection.fec"

	ferite_create_variable_accessors( script,
 var,
 reflection_variable_get,
 reflection_variable_set,
 reflection_variable_cleanup,
 self );
	FINCREF(self);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

