/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  reflection_Class.c */
/* class: Class */

#include <ferite.h>       /* we need this without a doubt */
#include "reflection_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_reflection_Class_getVariables_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 359 "reflection.fec"

		FeriteVariable *array = NULL, *var = NULL, *tmp = NULL;
		FeriteHashBucket *buk = NULL;
		FeriteIterator *iter = NULL;

		ChkSelf;
		array = ferite_create_uarray_variable(script, "Class::getVars", ClassObj->class_vars->size, FE_STATIC);
		iter = ferite_create_iterator(script);
		while((buk = (FeriteHashBucket*)ferite_hash_walk(script, ClassObj->class_vars,iter)) != NULL)
		{
			tmp = buk->data;
			var = fe_new_str(buk->id,ferite_variable_id_to_str( script, F_VAR_TYPE(tmp) ), 0, FE_CHARSET_DEFAULT);
			ferite_uarray_add(script,VAUA(array),var,buk->id, FE_ARRAY_ADD_AT_END );
		}
		ffree(iter);
		FE_RETURN_VAR(array);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_getClass_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 560 "reflection.fec"

		FeriteVariable *k = ferite_create_class_variable(script,"getClass()",ClassObj,FE_STATIC);
		FE_RETURN_VAR(k);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_serializeSleep_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 377 "reflection.fec"
 
		ferite_error(script,0,"Can not serialize reflection Classes\n");
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_fullyQualifiedName_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 571 "reflection.fec"

		char *n = ferite_generate_class_fqn( script, ClassObj );
		FE_RETURN_CSTR( n, FE_TRUE );
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_getFunctions_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 399 "reflection.fec"

		FeriteHashBucket *buk = NULL;
		FeriteVariable *array = NULL, *var = NULL;
		FeriteIterator *iter = NULL;
		FeriteFunction *func = NULL;

		ChkSelf;
		array = ferite_create_uarray_variable( script, "Class:getFunctions", ClassObj->class_methods->size, FE_STATIC);
		iter = ferite_create_iterator(script);
		while((buk = (FeriteHashBucket*)ferite_hash_walk(script,ClassObj->class_methods,iter)) != NULL)
		{
			func = buk->data;
			var = fe_new_str(buk->id,func->name, 0, FE_CHARSET_DEFAULT);
			ferite_uarray_add(script,VAUA(array),var,NULL,FE_ARRAY_ADD_AT_END);
		}
		ffree(iter);
		FE_RETURN_VAR(array);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_constructor_v )
{
   FeriteVariable *klass = params[0];
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, NULL );

   { /* Main function body. */
#line 331 "reflection.fec"

		if( F_VAR_TYPE(klass) != F_VAR_CLASS )
		{
			FE_RETURN_NULL_OBJECT;
		}
		self->odata = VAC(klass);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_newObject_E )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, NULL );

   { /* Main function body. */
#line 478 "reflection.fec"

		FeriteVariable *var = NULL;
		FeriteVariable **p = ferite_create_parameter_list( script, ferite_get_parameter_count( params ) + 1);
		int i = 0;

		for( i = 0; params[i] != NULL; i++ )
		{
			p[i] = ferite_duplicate_variable( script, params[i], NULL );
			MARK_VARIABLE_AS_DISPOSABLE( p[i] );
		}
		var = ferite_new_object( script, ClassObj, p );
		ferite_delete_parameter_list( script, p );
		if( var ) {
			FE_RETURN_VAR( var );
		}
		FE_RETURN_NULL_OBJECT;
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_classWithName_s )
{
   FeriteString *name = NULL;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 434 "reflection.fec"

	
		FeriteNamespaceBucket *nsb = ferite_find_namespace( script, script->mainns, name->data, FENS_CLS );
		FeriteNamespaceBucket *classnsb = ferite_find_namespace( script, script->mainns, "Class", FENS_CLS );
		if( nsb != NULL )
		{
			FeriteVariable **plist = ferite_create_parameter_list( script, 4 );
			FeriteVariable *rval = NULL;

			plist[0] = ferite_create_void_variable( script, "classWithName", FE_STATIC );
			plist[0]->type = F_VAR_CLASS;
			VAC(plist[0]) = nsb->data;
			MARK_VARIABLE_AS_DISPOSABLE(plist[0]);

			rval = ferite_new_object( script, classnsb->data, plist );
			ferite_delete_parameter_list( script, plist );

			if( rval != NULL )
			{
				FE_RETURN_VAR( rval );
			}
		}
		FE_RETURN_NULL_OBJECT;
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_name_v )
{
   FeriteVariable *k = params[0];
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 1, NULL );

   { /* Main function body. */
#line 539 "reflection.fec"

		char *name = NULL;		
		FeriteString *str = NULL;
		
		if( F_VAR_TYPE(k) != F_VAR_CLASS )
			str = ferite_str_new( script, "", 0, FE_CHARSET_DEFAULT );
		else
		{
			name = ferite_generate_class_fqn( script, VAC(k) );
			str = ferite_str_new( script, name, 0, FE_CHARSET_DEFAULT );
			ffree( name );
		}
		FE_RETURN_STR( str, FE_TRUE );		
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Class_locate_s )
{
   FeriteString *name = NULL;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 515 "reflection.fec"

		FeriteNamespaceBucket *nsb = ferite_find_namespace( script, script->mainns, name->data, FENS_CLS );
		if( nsb != NULL )
		{
			FeriteVariable *variable = ferite_create_class_variable( script, "classForString", nsb->data, FE_STATIC );
			FE_RETURN_VAR( variable );			
		}
		FE_RETURN_NULL_OBJECT;
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

