/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  reflection_Namespace.c */
/* class: Namespace */

#include <ferite.h>       /* we need this without a doubt */
#include "reflection_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getVariables_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 101 "reflection.fec"

		FeriteVariable *array = NULL, *var = NULL, *tmp = NULL;
		FeriteHashBucket *buk = NULL;
		FeriteIterator *iter = NULL;
		
		ChkSelf;
		array = ferite_create_uarray_variable(script, "ns::getVars", NSObj->data_fork->size, FE_STATIC);
		iter = ferite_create_iterator(script);
		while((buk = (FeriteHashBucket*)ferite_hash_walk(script, NSObj->data_fork,iter)) != NULL)
		{
			FeriteNamespaceBucket *b = buk->data;
			if( b->type == FENS_VAR )
			{
				tmp = b->data;
				var = fe_new_str(buk->id,ferite_variable_id_to_str( script, F_VAR_TYPE(tmp) ), 0, FE_CHARSET_DEFAULT);
				ferite_uarray_add(script,VAUA(array),var,buk->id, FE_ARRAY_ADD_AT_END );
			}
		}
		ffree(iter);
		FE_RETURN_VAR(array);		
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_serializeSleep_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 88 "reflection.fec"
 
		ferite_error(script,0,"Can not serialize reflection Namespaces\n");
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_fullyQualifiedName_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 251 "reflection.fec"
		
		char *n = ferite_generate_namespace_fqn( script, NSObj );
		FE_RETURN_CSTR( n, FE_TRUE );
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getNamespace_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 217 "reflection.fec"

		FeriteVariable *k = ferite_create_namespace_variable(script,"getNamespace()",NSObj,FE_STATIC);
		FE_RETURN_VAR(k);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getFunctions_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 184 "reflection.fec"

		FeriteVariable *v = reflection_ns_get_list( script, NSObj, FENS_FNC );
		FE_RETURN_VAR(v);		
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getNamespaces_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 206 "reflection.fec"

		FeriteVariable *v = reflection_ns_get_list( script, NSObj, FENS_NS );
		FE_RETURN_VAR(v);				
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getClasses_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 195 "reflection.fec"

		FeriteVariable *v = reflection_ns_get_list( script, NSObj, FENS_CLS );
		FE_RETURN_VAR(v);				
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getVariable_s )
{
   FeriteString *name = NULL;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 134 "reflection.fec"

		FeriteVariable *var = ferite_find_namespace_element_contents( script, NSObj, name->data, FENS_VAR );

		if( var == NULL ) {
			ferite_error( script, 0, "Namespace.getVariable(\"%s\") - No such variable in namespace\n", name->data );
			FE_RETURN_VOID;
		}
		/* We dont do FE_RETURN_VAR because we dont want the variable to be disposed */
		return var;
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_constructor_v )
{
   FeriteVariable *ns = params[0];
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, NULL );

   { /* Main function body. */
#line 80 "reflection.fec"

		if( F_VAR_TYPE(ns) != F_VAR_NS )
		{
			FE_RETURN_NULL_OBJECT;
		}
		self->odata = VAN(ns);
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_setVariable_sv )
{
   FeriteString *name = NULL;
   FeriteVariable *value = params[1];
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 2, &name, NULL );

   { /* Main function body. */
#line 158 "reflection.fec"

		FeriteVariable *rval = NULL;
		FeriteVariable *var = ferite_find_namespace_element_contents( script, NSObj, name->data, FENS_VAR );

		if( var == NULL ) {
			var = ferite_create_void_variable( script, name->data, FE_ALLOC );
			ferite_register_ns_variable( script, NSObj, name->data, var );
		}

		if( !ferite_types_are_equal( script, F_VAR_TYPE(var), F_VAR_TYPE(value) ) ) {
			ferite_error( script, 0, "Namespace.setVariable(\"%s\") - can't assign variable of type %s to type %s\n",
						 name->data,
						 ferite_variable_id_to_str( script, F_VAR_TYPE(value) ),
						 ferite_variable_id_to_str( script, F_VAR_TYPE(var) ) );
			FE_RETURN_VOID;
		}

		rval = ferite_op_assign( script, NULL, var, value );
		FE_RETURN_VAR( rval );
	
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_locate_s )
{
   FeriteString *name = NULL;
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   ferite_get_parameters( params, 1, &name );

   { /* Main function body. */
#line 297 "reflection.fec"

		FeriteNamespaceBucket *nsb = ferite_find_namespace( script, script->mainns, name->data, FENS_NS );
		if( nsb != NULL )
		{
			FeriteVariable *variable = ferite_create_namespace_variable( script, "classForString", nsb->data, FE_STATIC );
			FE_RETURN_VAR( variable );			
		}
		FE_RETURN_NULL_OBJECT;
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

FE_NATIVE_FUNCTION( ferite_reflection_Namespace_getScriptNamespace_ )
{
   FeriteClass *self = FE_CONTAINER_TO_CLASS;

   { /* Main function body. */
#line 229 "reflection.fec"

		FeriteVariable **params = fmalloc(sizeof(FeriteVariable*) * 2);
		FeriteVariable  *ns = NULL;
		
		params[0] = ferite_create_namespace_variable(script, "NS", script->mainns, FE_STATIC);
		MARK_VARIABLE_AS_DISPOSABLE(params[0]);
		params[1] = NULL;

		ns = ferite_new_object( script, self, params );
		ferite_delete_parameter_list( script, params );
		
		if( ns != NULL )
			FE_RETURN_VAR(ns);
		FE_RETURN_NULL_OBJECT;
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

