/* This file has been automatically generated by builder part of the ferite distribution */
/* file: reflection_Reflection.c */
/* namespace: Reflection */

#include <ferite.h>       /* we need this without a doubt */
#include "reflection_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_reflection_Reflection_type_v )
{
   FeriteVariable *var = params[0];
   FeriteNamespace *self = FE_CONTAINER_TO_NS;

   ferite_get_parameters( params, 1, NULL );

   { /* Main function body. */
#line 1339 "reflection.fec"

	FeriteVariable *v = NULL;
	char *value = NULL;

	if( F_VAR_TYPE(var) > 0 ) 
	value = ferite_variable_id_to_str( script, F_VAR_TYPE(var) );

	if( value != NULL )
 v = fe_new_str_static( "Reflection.type.return", value, 0, FE_CHARSET_DEFAULT );
	else
 v = fe_new_str_static( "Reflection.type.return", "", 0, FE_CHARSET_DEFAULT );

	MARK_VARIABLE_AS_DISPOSABLE( v );
	FE_RETURN_VAR( v );
	
   }
   FE_RETURN_VOID;
   self = NULL;
}

