/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "reflection_header.h"  /* this is the module header */

void ferite_reflection_register()
{
      ferite_module_register_native_function( "Reflection.type_v", ferite_reflection_Reflection_type_v );
      ferite_module_register_native_function( "Function.getReturnType_", ferite_reflection_Function_getReturnType_ );
      ferite_module_register_native_function( "Function.getParameterDetails_", ferite_reflection_Function_getParameterDetails_ );
      ferite_module_register_native_function( "Function.exec_E", ferite_reflection_Function_exec_E );
      ferite_module_register_native_function( "Function.serializeSleep_", ferite_reflection_Function_serializeSleep_ );
      ferite_module_register_native_function( "Function.isNative_", ferite_reflection_Function_isNative_ );
      ferite_module_register_native_function( "Function.execWithArray_a", ferite_reflection_Function_execWithArray_a );
      ferite_module_register_native_function( "Function.destructor_", ferite_reflection_Function_destructor_ );
      ferite_module_register_native_function( "Function.constructor_vs", ferite_reflection_Function_constructor_vs );
      ferite_module_register_native_function( "Function.constructor_s", ferite_reflection_Function_constructor_s );
      ferite_module_register_native_function( "Class.getVariables_", ferite_reflection_Class_getVariables_ );
      ferite_module_register_native_function( "Class.getClass_", ferite_reflection_Class_getClass_ );
      ferite_module_register_native_function( "Class.serializeSleep_", ferite_reflection_Class_serializeSleep_ );
      ferite_module_register_native_function( "Class.fullyQualifiedName_", ferite_reflection_Class_fullyQualifiedName_ );
      ferite_module_register_native_function( "Class.getFunctions_", ferite_reflection_Class_getFunctions_ );
      ferite_module_register_native_function( "Class.constructor_v", ferite_reflection_Class_constructor_v );
      ferite_module_register_native_function( "Class.newObject_E", ferite_reflection_Class_newObject_E );
      ferite_module_register_native_function( "Class.classWithName_s", ferite_reflection_Class_classWithName_s );
      ferite_module_register_native_function( "Class.name_v", ferite_reflection_Class_name_v );
      ferite_module_register_native_function( "Class.locate_s", ferite_reflection_Class_locate_s );
      ferite_module_register_native_function( "Namespace.getVariables_", ferite_reflection_Namespace_getVariables_ );
      ferite_module_register_native_function( "Namespace.serializeSleep_", ferite_reflection_Namespace_serializeSleep_ );
      ferite_module_register_native_function( "Namespace.fullyQualifiedName_", ferite_reflection_Namespace_fullyQualifiedName_ );
      ferite_module_register_native_function( "Namespace.getNamespace_", ferite_reflection_Namespace_getNamespace_ );
      ferite_module_register_native_function( "Namespace.getFunctions_", ferite_reflection_Namespace_getFunctions_ );
      ferite_module_register_native_function( "Namespace.getNamespaces_", ferite_reflection_Namespace_getNamespaces_ );
      ferite_module_register_native_function( "Namespace.getClasses_", ferite_reflection_Namespace_getClasses_ );
      ferite_module_register_native_function( "Namespace.getVariable_s", ferite_reflection_Namespace_getVariable_s );
      ferite_module_register_native_function( "Namespace.constructor_v", ferite_reflection_Namespace_constructor_v );
      ferite_module_register_native_function( "Namespace.setVariable_sv", ferite_reflection_Namespace_setVariable_sv );
      ferite_module_register_native_function( "Namespace.locate_s", ferite_reflection_Namespace_locate_s );
      ferite_module_register_native_function( "Namespace.getScriptNamespace_", ferite_reflection_Namespace_getScriptNamespace_ );
      ferite_module_register_native_function( "Variable.serializeSleep_", ferite_reflection_Variable_serializeSleep_ );
      ferite_module_register_native_function( "Variable.constructor_v", ferite_reflection_Variable_constructor_v );
      ferite_module_register_native_function( "Object.getVariables_", ferite_reflection_Object_getVariables_ );
      ferite_module_register_native_function( "Object.hasFunction_s", ferite_reflection_Object_hasFunction_s );
      ferite_module_register_native_function( "Object.serializeSleep_", ferite_reflection_Object_serializeSleep_ );
      ferite_module_register_native_function( "Object.className_", ferite_reflection_Object_className_ );
      ferite_module_register_native_function( "Object.setWeakReference_b", ferite_reflection_Object_setWeakReference_b );
      ferite_module_register_native_function( "Object.getVariable_s", ferite_reflection_Object_getVariable_s );
      ferite_module_register_native_function( "Object.setVariables_a", ferite_reflection_Object_setVariables_a );
      ferite_module_register_native_function( "Object.getObject_", ferite_reflection_Object_getObject_ );
      ferite_module_register_native_function( "Object.hasVariable_s", ferite_reflection_Object_hasVariable_s );
      ferite_module_register_native_function( "Object.destructor_", ferite_reflection_Object_destructor_ );
      ferite_module_register_native_function( "Object.constructor_o", ferite_reflection_Object_constructor_o );
      ferite_module_register_native_function( "Object.constructor_", ferite_reflection_Object_constructor_ );
      ferite_module_register_native_function( "Object.setVariable_sv", ferite_reflection_Object_setVariable_sv );
      ferite_module_register_native_function( "Object.hasMember_os", ferite_reflection_Object_hasMember_os );
      ferite_module_register_native_function( "Object.fromData_sa", ferite_reflection_Object_fromData_sa );
}

void ferite_reflection_init( FeriteScript *script )
{
}

void ferite_reflection_deinit( FeriteScript *script )
{
}

void ferite_reflection_unregister()
{
}

