/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  thread_Mutex.c */
/* class: Mutex */

#include <ferite.h>       /* we need this without a doubt */
#include "thread_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_thread_Mutex_unlock_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 264 "thread.fec"
 
	if( SelfMutex != NULL ) {
	aphex_mutex_unlock( SelfMutex );
	FE_RETURN_TRUE;
	}
	FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Mutex_lock_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 250 "thread.fec"

	if( SelfMutex != NULL ) {
	aphex_mutex_lock( SelfMutex );
	FE_RETURN_TRUE;
	}
	FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Mutex_destructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 236 "thread.fec"

 if( SelfMutex != NULL )
 aphex_mutex_destroy( SelfMutex );
 self->odata = NULL;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Mutex_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 230 "thread.fec"

 if( SelfMutex != NULL )
 self->odata = aphex_mutex_create();
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

