/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "thread_header.h"  /* this is the module header */

void ferite_thread_register()
{
      ferite_module_register_native_function( "Thread.sleep_n", ferite_thread_Thread_sleep_n );
      ferite_module_register_native_function( "Thread.start_n", ferite_thread_Thread_start_n );
      ferite_module_register_native_function( "Thread.isRunning_", ferite_thread_Thread_isRunning_ );
      ferite_module_register_native_function( "Thread.setPassExceptions_n", ferite_thread_Thread_setPassExceptions_n );
      ferite_module_register_native_function( "Thread.destructor_", ferite_thread_Thread_destructor_ );
      ferite_module_register_native_function( "Thread.constructor_", ferite_thread_Thread_constructor_ );
      ferite_module_register_native_function( "Thread.join_o", ferite_thread_Thread_join_o );
      ferite_module_register_native_function( "Event.timedWait_n", ferite_thread_Event_timedWait_n );
      ferite_module_register_native_function( "Event.signal_", ferite_thread_Event_signal_ );
      ferite_module_register_native_function( "Event.wait_", ferite_thread_Event_wait_ );
      ferite_module_register_native_function( "Event.destructor_", ferite_thread_Event_destructor_ );
      ferite_module_register_native_function( "Event.constructor_", ferite_thread_Event_constructor_ );
      ferite_module_register_native_function( "Mutex.unlock_", ferite_thread_Mutex_unlock_ );
      ferite_module_register_native_function( "Mutex.lock_", ferite_thread_Mutex_lock_ );
      ferite_module_register_native_function( "Mutex.destructor_", ferite_thread_Mutex_destructor_ );
      ferite_module_register_native_function( "Mutex.constructor_", ferite_thread_Mutex_constructor_ );
}

void ferite_thread_init( FeriteScript *script )
{
}

void ferite_thread_deinit( FeriteScript *script )
{
}

void ferite_thread_unregister()
{
}

