/* This file has been automatically generated by builder part of the ferite distribution */
/* file:  thread_Event.c */
/* class: Event */

#include <ferite.h>       /* we need this without a doubt */
#include "thread_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( ferite_thread_Event_timedWait_n )
{
   double seconds = 0.0;
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   ferite_get_parameters( params, 1, &seconds );

   { /* Main function body. */
#line 355 "thread.fec"

 if( SelfEvent != NULL )
 {
 if( aphex_event_timedwait( SelfEvent, (long)seconds) == 0)
 {
 FE_RETURN_TRUE;
 }
 }
 FE_RETURN_FALSE;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Event_signal_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 330 "thread.fec"

 
 if( SelfEvent != NULL )
 aphex_event_signal( SelfEvent );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Event_wait_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 341 "thread.fec"

 
 if( SelfEvent != NULL )
 aphex_event_wait( SelfEvent );
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Event_destructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 317 "thread.fec"

 if( SelfEvent != NULL )
 aphex_event_destroy( SelfEvent );
 self->odata = NULL;
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

FE_NATIVE_FUNCTION( ferite_thread_Event_constructor_ )
{
   FeriteObject *self = FE_CONTAINER_TO_OBJECT;
   FeriteObject *super = FE_CONTAINER_TO_OBJECT;

   { /* Main function body. */
#line 312 "thread.fec"

 self->odata = aphex_event_create();
 
   }
   FE_RETURN_VOID;
   self = NULL;
   super = NULL;
}

